// Module 1 · Your First Drive — universal skeleton.
import {
  lesson,
  why,
  rule,
  related,
  remember,
  trap,
  visual,
  image,
  recall,
  challenge,
  q,
} from '../helpers.mjs';

export const LESSONS = [
  lesson('traffic-signals', {
    title: 'The Light Changes. What Now?',
    objective: 'Traffic lights look simple. The situation around them may not be.',
    keyPoints: ['Read every signal.', 'Keep intersections clear.', 'Protect people in your path.'],
    challenge: challenge(
      'Your light is green, but traffic blocks the other side.',
      'What should you do?',
      ['Enter and wait inside', 'Stay behind the line', 'Honk and move forward'],
      1,
      'Stay out until your car can clear the intersection.',
      { image: 'traffic-signals-a01' },
    ),
    cards: [
      why('Green means check first', [
        'A green light lets you move only when the intersection is clear.',
        'Check the intersection before you go. “Green means go” is incomplete.',
        'Yield to pedestrians and traffic that still has priority.',
        'A protected movement and a permitted movement are not the same thing.',
      ]),
      rule('Let people clear the road', [
        'Someone may still be in the intersection.',
        'Let pedestrians, cyclists, and vehicles clear your path.',
        'Green allows movement, but it does not make a blocked or unsafe path legal.',
        'Do not enter if traffic will leave you stopped in the intersection.',
        'Check again before turning, especially for bicycles and pedestrians.',
      ]),
      image('traffic-signals-a02'),
      rule('Yellow means decide safely', [
        'Yellow means the light is changing. Stop if you can do it safely.',
        'A steady yellow warns that the green movement is ending and red will follow.',
        'Do not race the change. If you are too close to stop smoothly, continue through with care.',
        'The exam favors the driver who decides early, not the one who brakes at the last moment.',
      ]),
      rule('Red means stop', [
        'Make a complete stop at the stop line.',
        'Without a line, stop before the crosswalk; without a crosswalk, stop before you enter the intersection.',
        'A right turn on red is usually allowed after a full stop, unless a sign prohibits it.',
        'Even then you need a clear path and the proper yield to pedestrians and traffic.',
        'A red arrow means stop and wait until a signal permits that movement.',
      ]),
      recall('Recall · Right on red', 'Right on red is usually allowed after a full [[stop]] — unless a [[sign]] prohibits it.'),
      rule('Arrows control one direction', [
        'An arrow controls only the direction it points.',
        'A green arrow protects the turn while opposing traffic is held. A red arrow means stop and wait.',
        'Pedestrian indications control when people may start crossing.',
        'A countdown or a flashing hand does not give a turning driver permission to crowd someone who has not finished crossing.',
      ]),
      image('traffic-signals-a03'),
      rule('Flashing signals', [
        'Flashing red works like a STOP sign: stop at the lawful point, then go when it is safe.',
        'Flashing yellow means slow down and use caution. It does not require a stop.',
        'Overhead lane-control signals are different: green permits the lane, red closes it, and yellow warns of a change.',
      ]),
      recall('Recall · Flashing signals', 'Flashing [[red]] works like a STOP sign. Flashing [[yellow]] means slow down and use caution.'),
      rule('A dark signal', [
        'A signal that has lost power needs a cautious, predictable response.',
        'Slow down and prepare to stop. Treat the intersection like an all-way stop unless a sign or an officer directs otherwise.',
        'Take turns. Other drivers may read the dark signal differently, so expect hesitation.',
        'Do not assume another driver has noticed the outage.',
      ]),
      recall('Recall · Dark signal', 'A dark signal? Treat the intersection as an [[all-way stop]].'),
      remember('Remember the full picture', [
        'The light is only the first clue.',
        'Check arrows, signs, people, traffic, and the space ahead.',
        'First identify the indication, then the movement it controls, and finally the traffic or pedestrians you must still yield to.',
        'This three-step habit prevents most signal-question traps.',
      ]),
    ],
    test: [
      q('How should you handle the green-light turn?', ['Yield until the pedestrian is clear', 'Turn because green always protects the movement', 'Sound the horn and continue'], 0, 'Green permits movement, but turning traffic must still yield where the law requires.', { image: 'traffic-signals-q01-a' }),
      q('What does a steady yellow signal tell you?', ['The related green movement is ending', 'You have protected right-of-way', 'The signal is out of service'], 0, 'Steady yellow warns that the related green movement is ending and red will follow.', { image: 'traffic-signals-q02-a' }),
      q('A red arrow points right. What does it require?', ['Stop and wait for an indication permitting the movement', 'Nothing; every right turn on red is allowed', 'Flash your headlights and continue'], 0, 'A steady red arrow means stop; the movement waits until a permitting indication appears.', { image: 'traffic-signals-q03-a' }),
      q('What is required at a flashing red signal?', ['A full stop before proceeding when safe', 'Caution with no stop', 'Immediate acceleration'], 0, 'Flashing red uses the stop-sign rule.', { image: 'traffic-signals-q04-a' }),
      q('A pedestrian is still in the crosswalk as the countdown ends. What must a turning driver do?', ['Continue yielding until the path is safe', 'Use the ending countdown as permission to turn through', 'Pass behind the pedestrian without checking'], 0, 'Drivers must continue to protect a pedestrian lawfully in the roadway.', { image: 'traffic-signals-q05-a' }),
      q('Your light is green, but traffic is backed up across the intersection. What should you do?', ['Enter and wait in the intersection', 'Stay out until you can clear the intersection', 'Drive around the queue using the opposing lane'], 1, 'Do not enter an intersection unless there is enough space on the other side for your vehicle.'),
    ],
  }),

  lesson('stop-yield-entering-traffic', {
    title: 'STOP, YIELD, or Keep Going?',
    objective: 'Three simple controls can create very different decisions.',
    keyPoints: ['Stop in the right place.', 'Yield without forcing a gap.', 'Enter only when you can clear.'],
    challenge: challenge(
      'A YIELD sign faces you. Cross traffic is close.',
      'What should you do?',
      ['Keep your speed', 'Slow and stop if needed', 'Enter before the other car'],
      1,
      'Yield means give others the space they need. Stop when necessary.',
      { image: 'stop-yield-entering-traffic-a01' },
    ),
    cards: [
      rule('STOP means zero movement', [
        'Slow down early. Stop fully before moving again.',
        'After the complete stop, scan for vehicles, bicycles, and pedestrians.',
        'If a building or a parked vehicle blocks the view, move forward only as needed and only after protecting the crosswalk.',
        'A gap that existed when the wheels stopped can close before you move.',
      ]),
      rule('Use the first stopping point', [
        'At a STOP sign, stop at the marked stop line.',
        'If there is no line, stop before the near-side crosswalk.',
        'If neither exists, stop at the nearest point where you can see approaching traffic before entering the intersection.',
        'Keep the vehicle out of pedestrian space.',
      ]),
      recall('Recall · Stop position', 'Stop before the [[stop line]]. If there is no line, use the [[crosswalk]] or the intersection edge.'),
      image('stop-yield-entering-traffic-a02'),
      rule('A blocked view changes the next step', [
        'Make the required stop first. Then creep forward slowly for a better view.',
        'A blocked view does not erase the first required stop.',
        'After stopping and yielding, edge forward until you can see. Stop again if a new conflict appears.',
      ]),
      related('YIELD is not a rolling STOP', [
        'At a YIELD sign, slow to a reasonable speed, stop if necessary, and yield to traffic close enough to be an immediate hazard.',
        'Slow enough to judge the gap. Stop only when traffic or people require it.',
        'If the path is clearly open, an automatic stop is not required.',
        'If a safe gap does not exist, continue yielding.',
      ]),
      recall('Recall · YIELD meaning', 'YIELD means slow down, judge the [[gap]], and [[stop]] when traffic requires it.'),
      rule('Driveways join active traffic', [
        'People already on the road go first.',
        'Check sidewalks, bikes, and both traffic directions before you enter.',
        'One exam answer may stop in the right place but fail to yield before entering. Another may yield but block the crosswalk.',
        'A complete answer protects the stopping point and the moving path.',
      ]),
      recall('Recall · Driveways', 'Entering the road from a [[driveway]] or private property? Yield until it is [[safe]].'),
      image('stop-yield-entering-traffic-a03'),
      rule('Do not enter a trap', [
        'Wait when you cannot clear the intersection. The same idea applies at railroad tracks.',
        'A green light or your turn at a stop does not allow you to block the conflict area.',
        'Wait before an intersection when traffic is backed up beyond it.',
        'Wait before tracks until your entire vehicle can fit on the far side. Keep crosswalks clear.',
      ]),
      rule('Never force your priority', [
        'A correct rule cannot prevent another driver’s mistake. Yield again if a crash is developing.',
        'A driver leaving a driveway, alley, or private property must yield to nearby traffic and keep yielding until it is safe to enter.',
        'Cross the sidewalk only after checking for pedestrians, wheelchairs, and bicycles that may be hidden by walls or landscaping.',
      ]),
      remember('Remember this order', [
        'STOP, YIELD, and driveway questions use the same basic pattern.',
        'Control the car before the conflict. Then yield until it is safe to move.',
        'The stopping point and the later visibility check are separate steps.',
        'At a STOP or YIELD conflict, keep this order:',
      ], { bullets: ['Stop when required.', 'Look for conflicts.', 'Yield.', 'Then enter a clear space.'] }),
    ],
    test: [
      q('Where should you make the required stop?', ['Only after entering the intersection', 'Before entering the crosswalk', 'In the middle of the crosswalk'], 1, 'Without a stop line, stop before the near-side crosswalk.', { image: 'stop-yield-entering-traffic-q01-a' }),
      q('A stop line is painted before a crosswalk. Where do you stop?', ['Inside the crosswalk', 'At the far edge of the intersection', 'At the stop line'], 2, 'The marked stop line is the first lawful stopping point.', { image: 'stop-yield-entering-traffic-q02-a' }),
      q('Your view is blocked after a legal stop. What next?', ['Creep forward cautiously after checking the crosswalk', 'Accelerate into the intersection', 'Wait for the car behind to signal'], 0, 'After stopping, improve the view cautiously without taking pedestrian space.', { image: 'stop-yield-entering-traffic-q03-a' }),
      q('The yield-controlled road is completely clear. Must you always make a full stop?', ['Yes, every yield is a stop', 'No, and you may enter at any speed', 'No, but slow and proceed only when safe'], 2, 'YIELD requires giving way and stopping when necessary, not an automatic stop in every case.', { image: 'stop-yield-entering-traffic-q04-a' }),
      q('You are leaving a driveway across a sidewalk. Who has priority?', ['The largest vehicle', 'Sidewalk users and roadway traffic already present', 'The vehicle leaving the driveway'], 1, 'The entering driver yields to existing sidewalk and roadway traffic.', { image: 'stop-yield-entering-traffic-q05-a' }),
      q('After a complete stop, a building still blocks your view of cross traffic. What should you do?', ['Accelerate through before traffic arrives', 'Creep forward slowly after yielding until you can see', 'Sound the horn and enter without looking'], 1, 'After the required stop, move forward only as needed and continue checking for conflicts.'),
    ],
  }),

  lesson('turns-and-signals', {
    title: 'Make a Safe Turn',
    objective: 'A safe turn starts before the steering wheel moves.',
    keyPoints: ['Choose the correct lane.', 'Signal and check early.', 'Finish without drifting.'],
    challenge: challenge(
      'You plan to turn right across a bicycle lane.',
      'What comes first?',
      ['Check for cyclists', 'Move into the lane quickly', 'Wait until the last second to signal'],
      0,
      'Check the lane and blind spot. Yield before crossing it.',
      { image: 'turns-and-signals-a01' },
    ),
    cards: [
      why('A turn has four parts', [
        'Break every turn into the same short sequence.',
        'Choose the legal lane before the turn. Signal and reduce speed while checking all sides.',
        'Yield to pedestrians, bicycles, and opposing traffic. Complete the turn into a legal lane without drifting.',
        'Use the same four-part sequence for every turn:',
      ], { bullets: ['Choose the lane.', 'Signal.', 'Yield.', 'Finish in a legal lane.'] }),
      rule('Signal before the turn', [
        'Give other people time to react.',
        'In {{state}}, signal continuously during the final {{signal.turnDistanceFeet}} feet before the turn.',
        'For a lane change or any other sideways move, signal when another vehicle may be affected and move only when it is reasonably safe.',
        'A signal communicates intent. It does not order another road user to make space.',
      ]),
      recall('Recall · Signal timing', 'Signal continuously during the final [[{{signal.turnDistanceFeet}} feet]] before your turn.'),
      image('turns-and-signals-a02'),
      rule('Right turns start near the right edge', [
        'Move into the legal turn position early. Watch for cyclists between you and the curb.',
        'Right and left turns must begin and end from the positions the roadway requires.',
        'Do not swing wide from the wrong lane or cut across several lanes on the way out.',
        'Marked arrows, bicycle lanes, and double turn lanes can change the allowed path, so read them early.',
      ]),
      rule('Left turns cross more traffic', [
        'Yield to approaching traffic. Turn only when the gap is safe.',
        'A driver turning left or making a U-turn must yield to approaching traffic close enough to be hazardous.',
        'A circular green may permit the turn, but it does not protect it from oncoming traffic.',
        'After yielding, complete the turn only when it is reasonably safe.',
      ]),
      visual('Do not cut the corner', [
        'Stay on your side while entering the intersection. Finish in a lane that permits your movement.',
        'Good turns are prepared before the steering begins.',
        'The driver communicates, chooses the lawful starting position, clears pedestrians and traffic, and follows a predictable path into the correct lane.',
      ]),
      image('turns-and-signals-a03'),
      rule('One-way streets change the setup', [
        'Signs and arrows show the legal turn lane. Check the destination street before you move.',
        'A transit-only or bicycle lane is not a general travel lane, but a posted or legal exception may allow entry for a turn.',
        'Check signs and markings, enter only where and when permitted, and yield to users already in that lane.',
      ]),
      trap('Cancel the signal', [
        'A forgotten signal tells a false story. Make sure it turns off after the maneuver.',
        'The signal is not the maneuver.',
        'An answer can mention signaling and still be wrong if the lane, the blind-spot check, the yield, or the receiving path is unsafe.',
      ]),
      rule('Turn checklist', [
        'Use your left arm for hand signals. Hold it straight out for a left turn.',
        'Point it up for a right turn. Point it down to slow or stop.',
        'Before turning across a bicycle lane, check your mirrors and blind spot. Yield to any cyclist already in that space.',
        'Run through this checklist before and during the turn:',
      ], { bullets: ['Lane.', 'Signal.', 'Mirrors.', 'Blind spot.', 'Yield.', 'Turn.'] }),
      recall('Recall · Hand signals', 'Left arm straight out: [[left]] turn. Arm up: [[right]] turn. Arm down: [[slow]] or stop.'),
    ],
    test: [
      q('What is the safe lawful sequence?', ['Turn across the bicyclist’s path', 'Stop in the through lane and block traffic indefinitely', 'Yield to the bicyclist, enter the bike lane when safe, then turn'], 2, 'A turn across an adjacent bicycle lane requires a safe entry into the lane and protection of the bicyclist already there.', { image: 'turns-and-signals-q01-a' }),
      q('What is the safest general goal when completing a turn?', ['Change lanes in the middle of the turn', 'Enter the appropriate receiving lane predictably', 'Sweep across every open lane'], 1, 'A predictable turn begins and ends in the lawful lane position.', { image: 'turns-and-signals-q02-a' }),
      q('You have a circular green light and oncoming traffic is close. May you turn left across it?', ['No, yield until the turn is reasonably safe', 'Yes, green gives automatic protection', 'Yes, if you enter quickly'], 0, 'A permitted left turn still yields to hazardous approaching traffic.', { image: 'turns-and-signals-q03-a' }),
      q('How long before a turn must the signal be continuous in {{state}}?', ['For exactly one second', 'During the final {{signal.turnDistanceFeet}} feet', 'Only after the turn begins'], 1, '{{state}} requires a continuous signal during the final {{signal.turnDistanceFeet}} feet before the turn.', { image: 'turns-and-signals-q04-a' }),
      q('A driver’s left arm points downward. What is being signaled?', ['A right turn', 'A left turn', 'Slowing or stopping'], 2, 'A downward left arm signals slowing or stopping.', { image: 'turns-and-signals-q05-a' }),
      q('Before crossing a bicycle lane to make a permitted right turn, what must you do?', ['Stop in the travel lane until every bicycle is out of sight', 'Check for and yield to bicyclists before entering the lane legally', 'Use the bicycle lane as a passing lane'], 1, 'Enter a bicycle lane for a turn only where allowed, after checking for and yielding to bicyclists.'),
    ],
  }),

  lesson('speed-and-space', {
    title: 'Keep Space Around Your Car',
    objective: 'Speed and distance buy you time when something changes.',
    keyPoints: ['Choose a safe speed.', 'Scan beyond the next car.', 'Protect an escape space.'],
    challenge: challenge(
      'The limit is {{speed.maxMph}} mph. Heavy fog hides the road ahead.',
      'Which speed should you choose?',
      ['Exactly {{speed.maxMph}} mph', 'A lower speed you can control', 'The speed of the fastest car'],
      1,
      'The posted limit is a maximum. Conditions may require less.',
      { image: 'speed-laws-a01' },
    ),
    cards: [
      why('The limit is not a target', [
        'A posted limit assumes good conditions. Rain, fog, traffic, or glare may require less.',
        'Slow for rain, fog, darkness, curves, hills, traffic, and road work.',
        'Choose a speed that lets you stop within the distance you can see.',
        'Never drive faster than is safe for current conditions.',
      ]),
      rule('The basic speed rule', [
        'Every state has a basic speed rule: never drive faster than conditions allow.',
        'You can be too fast below the posted limit.',
        'Consider weather, visibility, traffic, the road surface, and the width of the road.',
        'A posted maximum is not a command to maintain that speed.',
      ]),
      recall('Recall · Basic speed rule', 'Never drive faster than is [[safe]] for current conditions, even below the posted [[limit]].'),
      rule('Know the default limits', [
        'Some limits apply even when no sign repeats them.',
        'In {{state}}, the limit in business and residential districts is {{speed.residentialMph}} mph unless a sign says otherwise.',
        'The general maximum on highways is {{speed.maxMph}} mph. On a two-lane undivided highway it is {{speed.twoLaneUndividedMph}} mph unless a higher limit is posted.',
        'A higher limit applies only where it is lawfully posted on an eligible highway.',
      ]),
      visual('Look beyond the next car', [
        'Scan far enough to see trouble early. Early changes are smoother and safer.',
        'Keep your eyes moving ahead, to the sides, behind, and through intersections.',
        'A hazard seen early usually needs a small response.',
        'The same hazard discovered at the bumper needs a hard response and may leave no safe path.',
      ]),
      rule('Leave a time gap', [
        'Pick a fixed point ahead. Count after the vehicle in front passes it.',
        'Keep at least {{following.seconds}} seconds between you and the car ahead in good conditions.',
        'Add more time when risk grows: poor weather, darkness, a motorcycle ahead, or a large vehicle that blocks your view.',
        'Following more closely than is reasonable for the speed and the conditions is against the law.',
      ]),
      recall('Recall · Following gap', 'Keep at least [[{{following.seconds}} seconds]] behind the car ahead, and add more in bad conditions.'),
      visual('Stopping takes three stages', [
        'The car travels while you perceive the hazard, while you decide and react, and while the brakes reduce speed.',
        'Higher speed and poor traction enlarge the total space.',
        'Looking farther ahead does not shorten braking physics, but it lets you begin sooner.',
        'Total stopping distance has three stages:',
      ], { bullets: ['First you see the problem.', 'Then you react.', 'Only then do the brakes slow the car.'] }),
      recall('Recall · Stopping distance', 'You stop in three stages: you [[see]] the problem, you [[react]], and only then the brakes slow the car.'),
      rule('Keep an escape space', [
        'Avoid sitting beside another vehicle. Leave room to move if traffic stops suddenly.',
        'Leave room around parked cars, merging traffic, bicycles, and uncertain drivers.',
        'If a conflict develops ahead, a usable side space may prevent a rear-end collision when braking alone is not enough.',
      ]),
      trap('Handle a tailgater calmly', [
        'Create more room ahead. Change lanes or use a turnout when safe.',
        'Do not brake-check. Trying to teach a close follower a lesson increases the danger.',
        'Increase the space ahead so you can slow gradually.',
        'Avoid sudden braking, speeding up, or blocking a pass.',
      ]),
      remember('Remember the goal', [
        'See early. Leave space.',
        'Slow before the situation becomes urgent.',
        'Open space gives you time to notice a problem and respond smoothly.',
        'The goal is not to protect one memorized number.',
        'It is to keep enough room to notice, decide, brake, or steer without passing the emergency to another road user.',
      ]),
    ],
    test: [
      q('Which speed rule controls your decision?', ['Follow the fastest nearby driver', 'Slow below the posted limit to a speed reasonable for conditions', 'Drive exactly the posted maximum'], 1, 'The basic speed rule requires a reasonable and prudent speed for current conditions.', { image: 'speed-laws-a01' }),
      q('May you be driving too fast while below the posted limit?', ['Yes, when conditions make that speed unsafe', 'No, the sign is the only factor', 'Only in a school zone'], 0, 'Conditions can make a below-limit speed unreasonable or dangerous.', { image: 'speed-laws-a01' }),
      q('When does a limit above the general maximum apply?', ['On every freeway', 'Whenever traffic is light', 'Only where it is lawfully posted on an eligible highway'], 2, 'A higher limit is not a statewide default; it must be lawfully posted on an eligible highway.'),
      q('How should the rain change your following gap?', ['Increase the following space', 'Keep the same gap because it was safe before', 'Move closer so another car cannot merge'], 0, 'Following distance must remain reasonable for speed, traffic, and roadway conditions.', { image: 'following-distance-scanning-a01' }),
      q('Why scan beyond the vehicle directly ahead?', ['To choose a radio station', 'To detect developing hazards before they demand an abrupt response', 'To ignore nearby traffic'], 1, 'Early detection preserves time and gentler options.', { image: 'following-distance-scanning-a01' }),
      q('A driver is following too closely behind you. What is the safest response?', ['Brake sharply to make the driver back off', 'Increase space ahead and let the driver pass when safe', 'Speed far above the limit'], 1, 'Create more room ahead and allow the tailgater to pass safely instead of escalating the risk.'),
    ],
  }),
];
