// Module 5 · Share the Road — universal skeleton.
import {
  lesson,
  why,
  rule,
  related,
  remember,
  trap,
  visual,
  image,
  recall,
  challenge,
  q,
} from '../helpers.mjs';

export const LESSONS = [
  lesson('bicycles-motorcycles', {
    title: 'Bicycles and Motorcycles',
    objective: 'Smaller road users are easy to hide and easy to injure.',
    keyPoints: ['Search every blind spot.', 'Give real passing space.', 'Respect the full lane.'],
    challenge: challenge(
      'You plan to open a door beside moving traffic.',
      'What should you check?',
      ['Only the front mirror', 'Behind you for bikes and motorcycles', 'Only the sidewalk'],
      1,
      'A rider may be beside the vehicle. Check before opening the door.',
      { image: 'bicycles-motorcycles-a01' },
    ),
    cards: [
      why('Look where riders can disappear', [
        'Check mirrors and blind spots. Look again before turning or changing lanes.',
        'Before entering or crossing a bicycle lane, check for a rider beside or behind you.',
        'Merge behind the bicyclist when necessary rather than turning across the rider’s path.',
        'A signal does not make the bicycle disappear.',
      ]),
      rule('Bicycle lanes carry traffic', [
        'A cyclist may approach from behind. Yield before crossing the lane.',
        'Bicycles and motorcycles are narrow, easy to hide, and entitled to road space.',
        'The safest driver detects them before turning or changing lanes and never uses their small size as an excuse for a small margin.',
      ]),
      image('bicycles-motorcycles-a02'),
      visual('Expect movement away from the edge', [
        'Debris, drains, and parked doors can push a cyclist left. Leave room.',
        'A bicyclist may be beside you even when the travel lane looked clear a moment ago.',
        'Check the bicycle lane and the right-side blind spot before turning. Look behind before opening a door next to traffic.',
      ]),
      rule('Pass with space', [
        'When passing a bicycle in {{state}}, keep at least {{bicycle.passingFeet}} feet of clearance.',
        'When it is safe and legal, change lanes to pass a bicyclist instead of squeezing by in the same lane.',
        'If neither option can be completed without danger, slow and remain behind until the situation improves.',
        'Wait for a gap that lets you move over fully, then pass without lingering beside the rider.',
      ]),
      recall('Recall · Passing a bicycle', 'Give a bicycle at least [[{{bicycle.passingFeet}} feet]] of clearance when passing — slow down if you cannot.'),
      visual('A motorcycle owns its lane', [
        'Do not squeeze beside it. Use a normal lane-change gap.',
        'Motorcycles can disappear in blind spots and can look farther away or slower than they are.',
        'Look again before changing lanes. Leave a safe following gap.',
        'Never squeeze past a motorcycle while both vehicles are in one lane. Road defects may require a rider to shift position quickly.',
      ]),
      image('bicycles-motorcycles-a03'),
      rule('Their speed is hard to judge', [
        'A narrow profile looks farther away. Check twice before turning across its path.',
        'Give a full lane and normal following space.',
        'In slow traffic a motorcycle may still be moving faster than the queue, so check the blind spot directly before any sideways move.',
      ]),
      recall('Recall · Sharing lanes', 'A motorcycle is entitled to its [[full lane]]. Never pass it inside the same [[lane]].'),
      remember('The safety rule is simple', [
        'Search longer and leave more room.',
        'Never assume the rider saw you.',
        'A bicycle or a motorcycle is not required to vanish because your turn or pass would be convenient.',
        'Questions often test whether you wait for a safe gap instead of compressing a vulnerable road user.',
      ]),
    ],
    test: [
      q('How should you handle the bicyclist with oncoming traffic present?', ['Squeeze between the bicycle and the oncoming car', 'Sound the horn and force the bicyclist off the lane', 'Wait behind the bicyclist until a safe pass is available'], 2, 'If lawful clearance cannot be provided, slow and wait rather than endanger the bicyclist.', { image: 'bicycles-motorcycles-a01' }),
      q('What is the minimum bicycle passing clearance in {{state}}?', ['One foot', 'Six inches', '{{bicycle.passingFeet}} feet'], 2, '{{state}} requires at least {{bicycle.passingFeet}} feet when passing a bicycle.', { image: 'bicycles-motorcycles-a01' }),
      q('A bicyclist is beside you as you prepare to turn right. What should you do?', ['Move closer to the curb', 'Yield and merge behind when safe', 'Turn across the bicycle'], 1, 'Protect the bicyclist already occupying the path before entering the lane for the turn.', { image: 'bicycles-motorcycles-a02' }),
      q('May you pass a motorcycle while staying beside it in the same lane?', ['No', 'Yes, if the lane is wide', 'Only on a freeway'], 0, 'Do not crowd or pass a motorcycle within the same lane.', { image: 'bicycles-motorcycles-a03' }),
      q('Traffic is nearly stopped. Why is a motorcycle still a risk before you change lanes?', ['Mirrors cover every possible position', 'It can hide in a blind spot and move faster than the queue', 'Motorcycles are prohibited from moving'], 1, 'A motorcycle may be closing in a blind spot, so direct observation remains important in slow traffic.', { image: 'bicycles-motorcycles-a03' }),
      q('Before turning right across a bicycle lane, where should you check?', ['Only the rearview mirror', 'Mirrors and the right-side blind spot for bicyclists', 'Only the traffic signal'], 1, 'A bicyclist can be beside your vehicle, so check mirrors and the blind spot before crossing the lane.'),
    ],
  }),

  lesson('trucks-buses-slow-vehicles', {
    title: 'Trucks, Buses, and Slow Vehicles',
    objective: 'Large vehicles need more room. Slow vehicles change closing speed.',
    keyPoints: ['Stay out of no-zones.', 'Expect wide turns.', 'Plan before passing.'],
    challenge: challenge(
      'A truck starts a wide right turn.',
      'Where should you be?',
      ['Beside the truck', 'Behind its turning path', 'Between the truck and curb'],
      1,
      'Stay back. The trailer can close the space beside it.',
      { image: 'trucks-buses-slow-vehicles-a01' },
    ),
    cards: [
      why('Large vehicles have large blind spots', [
        'If you cannot see the driver in a mirror, the driver may not see you. Move out of the no-zone.',
        'A large vehicle can have extensive blind areas immediately in front, behind, and along both sides.',
        'Avoid lingering there, and do not cut closely in front after passing.',
      ]),
      rule('They need more stopping room', [
        'Do not cut closely in front. Leave extra space after passing.',
        'A truck driver may be unable to see a car close to the front, rear, or sides.',
        'Leave extra room on grades and at stops, because a heavy vehicle needs more space to slow.',
      ]),
      recall('Recall · Truck blind spots', 'If you cannot see the truck driver in a [[mirror]], the driver may not see [[you]].'),
      image('trucks-buses-slow-vehicles-a02'),
      visual('Wide turns use two paths', [
        'The cab may first swing away from the direction of the turn. The rear wheels may track close to the curb.',
        'Never enter the space between a turning large vehicle and the curb. Wait until the complete vehicle clears the path.',
        'The open space beside a large vehicle may be space the vehicle is about to use.',
        'Road geometry, not impatience, predicts the conflict.',
      ]),
      recall('Recall · Cutting in', 'Never cut [[closely]] in front of a truck — it needs far more [[stopping room]].'),
      rule('Pass without lingering', [
        'Move through the blind spot steadily. Return only when the truck is clearly visible in your mirror.',
        'Buses, streetcars, and light rail follow routes that can place passengers or rails beside ordinary traffic.',
        'Follow signs, signals, lane markings, and boarding-island rules.',
        'Watch for passengers crossing between a curb and a transit stop.',
      ]),
      visual('Slow vehicles change your timing', [
        'You may close the gap faster than expected. Brake early and wait for a legal pass.',
        'Large vehicles follow the same road rules but need different geometry: wider turns, larger blind areas, and more stopping space.',
        'Slow vehicles and animals add another lesson: predict movement before you arrive beside it.',
      ]),
      image('trucks-buses-slow-vehicles-a03'),
      rule('An orange triangle means very slow', [
        'A slow-moving vehicle emblem is an orange and red triangle on the back.',
        'It marks machines that usually travel {{smv.maxMph}} mph or less, like farm or road equipment.',
        'Spot it early and slow smoothly. Pass only when the law and your view allow.',
      ]),
      recall('Recall · Orange triangle', 'An orange and red [[triangle]] marks a slow-moving vehicle — usually [[{{smv.maxMph}}]] mph or less.'),
      rule('Animals can react suddenly', [
        'Slow down near riders or livestock. Follow the rider’s signal when an animal is frightened.',
        'Near horses or livestock, reduce speed or stop as needed and follow the handler’s directions.',
        'Avoid horns, revving, or abrupt movement that can frighten an animal.',
      ]),
      remember('Give size the space it needs', [
        'More room helps everyone see, stop, and turn.',
        'A heavy vehicle may need more room to slow and may gain speed downhill.',
        'After passing, remain ahead long enough to create a usable gap before returning.',
        'When following, leave space so you can see around the vehicle and react without relying on its driver.',
      ]),
    ],
    test: [
      q('How should you respond to the truck’s wide right turn?', ['Pass on the sidewalk', 'Stay back and outside the truck’s turning path', 'Drive into the open space'], 1, 'Large vehicles may move left to create turning room; the space on the right can become a squeeze zone.', { image: 'trucks-buses-slow-vehicles-a01' }),
      q('You cannot see the truck driver in the side mirror. What should you assume?', ['You automatically have right-of-way', 'The driver may not see you', 'The mirror is decorative'], 1, 'Lack of mirror visibility is a strong cue that your vehicle may be in the truck’s blind area.', { image: 'trucks-buses-slow-vehicles-a01' }),
      q('Why should you not move beside a truck turning right?', ['The truck must stop halfway', 'Your lane always ends', 'The rear wheels may track into that space'], 2, 'The truck’s rear path can close the apparent gap beside the curb.', { image: 'trucks-buses-slow-vehicles-a02' }),
      q('After passing a large truck, when should you return to its lane?', ['When your rear bumper reaches its front bumper', 'After creating a safe clear gap', 'Immediately beside the cab'], 1, 'Cutting in closely removes the large vehicle’s stopping margin.', { image: 'trucks-buses-slow-vehicles-a03' }),
      q('A rider signals you to stop near a frightened horse. What should you do?', ['Pass as closely as possible', 'Stop and follow the handler’s direction', 'Sound the horn'], 1, 'Control speed or stop as necessary to protect the person and the animal.', { image: 'trucks-buses-slow-vehicles-a03' }),
      q('A truck begins a wide right turn. What should you do?', ['Drive into the space on its right', 'Stay back and out of the truck’s turning path', 'Pass between the truck and curb'], 1, 'A truck may swing wide and then close the space beside it. Never squeeze into that path.'),
    ],
  }),

  lesson('school-buses-emergency-vehicles', {
    title: 'School Buses and Emergency Vehicles',
    objective: 'Some vehicles and people need the road cleared immediately.',
    keyPoints: ['Make a predictable path.', 'Stop for school-bus red lights.', 'Protect stopped responders.'],
    challenge: challenge(
      'An ambulance approaches from behind with lights and siren.',
      'What should you do?',
      ['Speed up', 'Move right and stop safely', 'Stop inside the intersection'],
      1,
      'Make a clear path. Avoid stopping where you block the intersection.',
      { image: 'emergency-school-work-zones-a01' },
    ),
    cards: [
      rule('Emergency vehicles need a clear path', [
        'When an emergency vehicle approaches with lights or a siren, move toward the right edge and stop.',
        'Stop away from intersections and wait until it passes. Follow any officer’s directions.',
        'If you are already in an intersection, clear it before pulling over.',
      ]),
      recall('Recall · Emergency vehicles', 'Emergency vehicle with lights or siren? Pull to the [[right]] edge and [[stop]] clear of intersections.'),
      rule('Do not stop in the conflict', [
        'Clear the intersection first when necessary. Then stop where responders can pass.',
        'Look for more responders. One vehicle may be followed by several more.',
        'Check around you before moving toward the required side and stopping.',
        'After it passes, check for additional responders before reentering traffic.',
      ]),
      image('emergency-school-work-zones-a02'),
      rule('Protect vehicles stopped on the roadside', [
        'Approaching a stopped emergency or service vehicle with warning lights, move into a lane that is not next to it when it is safe and legal.',
        'If you cannot move over, slow to a reasonable and prudent speed.',
        'The rule protects officers, tow operators, road workers, and anyone else working beside traffic.',
      ]),
      recall('Recall · Move over', 'Passing a stopped vehicle with warning lights: move to a [[nonadjacent]] lane, or [[slow]] to a safe speed.'),
      rule('Do not follow the response', [
        'Stay at least {{emergency.followFeet}} feet behind a responding emergency vehicle unless you are authorized.',
        'Give the scene room. Extra space keeps the route and the scene available to responders.',
        'Never drive over an unprotected fire hose unless the fire official in charge allows it.',
      ]),
      rule('School-bus red lights mean stop', [
        'Stop when a school bus flashes red lights or extends its stop arm. Watch for children crossing.',
        'Stay stopped until the warning ends.',
        'A divided road can change who must stop. Read the median and the road design carefully.',
        'Do not invent an exception on an ordinary road.',
      ]),
      recall('Recall · School bus', 'Flashing [[red]] school-bus lights mean stop — and stay stopped until the signal [[ends]].'),
      image('emergency-school-work-zones-a03'),
      rule('People can control traffic too', [
        'Follow authorized crossing guards and officers. Stay stopped until they release your movement.',
        'A crossing guard, a flagger, or an officer may direct traffic through a temporary pattern.',
        'Obey the person’s signal even when it differs from the normal signal or lane.',
        'Slow early and expect workers, children, equipment, or stopped traffic. Do not resume normal speed until you are clear of the controlled area.',
      ]),
    ],
    test: [
      q('Where should you make room for the approaching ambulance?', ['Stop immediately inside the intersection', 'Race the ambulance', 'Clear the intersection, then move right and stop when safe'], 2, 'Do not block the intersection; clear it, then move toward the right edge and stop when safe.', { image: 'emergency-school-work-zones-a01' }),
      q('Where should you stop for an approaching emergency vehicle?', ['In the center of the intersection', 'In the left lane', 'Near the right edge and clear of intersections'], 2, 'Move toward the right edge and remain clear of the intersection.', { image: 'emergency-school-work-zones-a01' }),
      q('You cannot safely change lanes away from a stopped vehicle with warning lights. What next?', ['Slow to a reasonable safe speed', 'Maintain speed regardless of conditions', 'Stop in the travel lane'], 0, 'When a lawful lane move is not practicable, the alternative is a reasonable and prudent safe speed.', { image: 'emergency-school-work-zones-a02' }),
      q('How closely may an ordinary driver follow a responding emergency vehicle in {{state}}?', ['Closer than one car length', 'Any distance if the hazard lights are on', 'Not within {{emergency.followFeet}} feet'], 2, 'The minimum following distance behind a responding emergency vehicle is {{emergency.followFeet}} feet.', { image: 'emergency-school-work-zones-a03' }),
      q('When may you proceed after stopping for a school bus’s red signals?', ['As soon as one child reaches the curb', 'When the driver behind honks', 'When the red signal and stop-arm requirement has ended and the path is safe'], 2, 'Remain stopped until the school-bus signal ceases, subject to the roadway exceptions.', { image: 'emergency-school-work-zones-a03' }),
      q('A crossing guard tells you to wait. What should you do?', ['Follow the guard', 'Follow the nearest driver', 'Continue if your lane looks clear'], 0, 'An authorized crossing guard controls traffic at that moment.'),
    ],
  }),

  lesson('rail-light-rail-work-zones', {
    title: 'Railroads, Light Rail, and Work Zones',
    objective: 'Tracks and temporary lanes punish last-second decisions.',
    keyPoints: ['Keep an exit beyond tracks.', 'Never bypass a gate.', 'Follow temporary controls.'],
    challenge: challenge(
      'Traffic is stopped just beyond railroad tracks.',
      'May you enter the crossing?',
      ['Yes, if no train is visible', 'Only when your car can clear', 'Yes, after the gate rises'],
      1,
      'Do not enter until the whole vehicle can fit beyond the tracks.',
      { image: 'rail-light-rail-work-zones-ca-warning-and-guide-signs-a01' },
    ),
    cards: [
      rule('Tracks need an exit', [
        'Check the space beyond the rails. Wait before the crossing when traffic is backed up.',
        'Do not start across tracks unless there is enough room for your whole vehicle on the far side.',
        'Stop when required by a signal, a gate, a flagger, or an approaching rail vehicle.',
        'Never drive around, under, or through a closed or moving gate.',
      ]),
      recall('Recall · Rail crossings', 'Cross the tracks only when you can see a clear [[exit]] on the other side.'),
      rule('A train cannot avoid you', [
        'Never race it. Stop for lights, gates, flaggers, and an approaching train.',
        'Never go around a gate. A second train may be hidden behind the first.',
        'Wait until the control fully allows movement.',
        'If the vehicle stalls on the tracks, get everyone out immediately and away from the rails. Use the crossing emergency sign, then call 911.',
      ]),
      recall('Recall · Stalled on tracks', 'Stalled on the tracks? Get everyone [[out]] and away immediately.'),
      image('rail-light-rail-work-zones-ca-warning-and-guide-signs-a02'),
      rule('Light rail shares city space', [
        'Check signals, signs, and the rail path. Never turn in front of an approaching rail vehicle.',
        'Buses, streetcars, and light rail follow routes that can place passengers or rails beside ordinary traffic.',
        'Follow signs, signals, lane markings, and boarding-island rules.',
        'Watch for passengers crossing between a curb and a transit stop.',
      ]),
      rule('Orange means the road may change', [
        'Expect narrow lanes, workers, equipment, and sudden queues. Slow down early.',
        'A flagger or an officer may direct traffic through a temporary pattern.',
        'Obey the person’s signal even when it differs from the normal signal or lane.',
        'Fines for violations in a work zone are often higher, and the danger to workers is real.',
      ]),
      rule('Flaggers give real directions', [
        'Follow the flagger even when the usual signal differs. Do not move until released.',
        'In work zones, follow temporary signs, channelizing devices, and flagger directions.',
        'Expect narrowed lanes, sudden slowing, and equipment entering from the side.',
        'A flagger’s STOP paddle is a stop sign held by a person; a SLOW paddle means proceed at the posted work-zone speed.',
      ]),
      image('rail-light-rail-work-zones-ca-warning-and-guide-signs-a03'),
      remember('Leave the work zone calmly', [
        'Keep the lower safe speed until you are fully clear. Watch for traffic merging back.',
        'Work-zone signs, cones, drums, barriers, arrow boards, and flaggers can replace the normal path.',
        'Reduce speed for the actual conditions, increase space, and follow the temporary channel.',
      ]),
    ],
    test: [
      q('Traffic is stopped just beyond the tracks. What should you do?', ['Drive around the lowered gate', 'Wait before the tracks until enough space opens', 'Follow the car ahead onto the tracks'], 1, 'Do not enter tracks without enough room to clear them completely.', { image: 'rail-light-rail-work-zones-ca-warning-and-guide-signs-q04-a' }),
      q('A flagger directs traffic through a temporary lane. What should you follow?', ['The flagger and temporary controls', 'The faded permanent line only', 'The route chosen by the car behind'], 0, 'Authorized temporary controls define the safe work-zone path.', { image: 'rail-light-rail-work-zones-ca-warning-and-guide-signs-q05-a' }),
      q('Traffic is stopped just beyond railroad tracks. When may you enter the crossing?', ['As soon as the vehicle ahead begins moving', 'Only when there is enough room to clear the tracks completely', 'Whenever no train is visible'], 1, 'You need a clear space beyond the tracks before entering, even when no train is currently visible.'),
      q('A work-zone flagger signals you to stop even though the nearby light is green. What should you do?', ['Follow the green light', 'Stop as directed by the flagger', 'Drive around the flagger'], 1, 'Authorized temporary traffic direction controls the movement through the work area.'),
      q('May you drive around a lowered railroad gate when no train is visible?', ['Yes', 'No', 'Only after honking'], 1, 'Never drive around, under, or through a closed or moving gate.'),
      q('Before turning across light-rail tracks, what should you check?', ['Only the traffic light', 'The rail vehicle’s path and every control', 'Only the car behind you'], 1, 'A rail vehicle cannot steer away. Check its path before crossing.'),
    ],
  }),
];
