// Module 6 · When Driving Gets Hard — universal skeleton.
import {
  lesson,
  why,
  rule,
  related,
  remember,
  trap,
  visual,
  image,
  recall,
  challenge,
  q,
} from '../helpers.mjs';

export const LESSONS = [
  lesson('driving-after-dark', {
    title: 'Driving After Dark',
    objective: 'At night, you must control speed with the road you can actually see.',
    keyPoints: ['Use the correct lights.', 'Dim high beams early.', 'Slow when sight distance shrinks.'],
    challenge: challenge(
      'Your headlights cannot show enough road for your current stopping distance.',
      'What should you change?',
      ['Your speed', 'Your radio', 'Your lane only'],
      0,
      'Slow down until the visible road is long enough for a safe stop.',
      { image: 'night-weather-visibility-a01' },
    ),
    cards: [
      why('Headlights help others see you', [
        'They do more than light the road. Use them whenever visibility rules require.',
        'Never drive faster than is reasonable for darkness, fog, smoke, rain, glare, or traffic.',
        'Keep stopping distance within the visible usable path.',
        'If you cannot see enough road to stop safely, reduce speed further or leave the roadway at a safe place.',
      ]),
      rule('Headlights run on a clock too', [
        'In {{state}}, headlights go on {{lights.afterSunsetMinutes}} minutes after sunset and stay on until {{lights.beforeSunriseMinutes}} minutes before sunrise.',
        'They are also required whenever you cannot see people or vehicles clearly {{lights.visibilityFeet}} feet ahead.',
        'The clock applies even when the sky still looks bright. An exam answer like “only when it is fully dark” is wrong.',
      ]),
      image('night-weather-visibility-a02'),
      visual('Do not outrun your lights', [
        'You need enough visible road to stop. Slow down before dark curves and hills.',
        'If your stopping distance is longer than your visible road, a hidden hazard can become unavoidable.',
        'Use low beams in fog or smoke, because high beams reflect light back.',
        'Keep the windshield, lights, mirrors, and wipers clean and working.',
      ]),
      recall('Recall · Outdriving your lights', 'Do not outrun your headlights — be able to [[stop]] inside the distance you can [[see]].'),
      rule('High beams have limits', [
        'Dim within {{highBeam.approachingFeet}} feet of an approaching vehicle.',
        'Dim within {{highBeam.followingFeet}} feet when following another vehicle.',
        'Looking toward the right edge can reduce glare from an oncoming driver, but you must still hold your lane and a speed that fits what you can see.',
      ]),
      recall('Recall · Headlight hours', 'Headlights on from [[{{lights.afterSunsetMinutes}} minutes]] after sunset until {{lights.beforeSunriseMinutes}} minutes before [[sunrise]].'),
      visual('Glare steals detail', [
        'Look toward the right road edge. Reduce speed without staring at oncoming lights.',
        'Sun glare, dust, snow, flooding, or strong wind can remove your normal safety margin.',
        'Slow smoothly and increase following distance.',
        'If you cannot see well enough to drive, leave the roadway at a safe place and wait.',
      ]),
      recall('Recall · High beams', 'Dim within [[{{highBeam.approachingFeet}} feet]] of an approaching vehicle and within [[{{highBeam.followingFeet}} feet]] when following.'),
      image('night-weather-visibility-a03'),
      trap('Interior light can hurt night vision', [
        'Keep the dashboard readable but not bright. Put the phone away.',
        'Clean glass matters. Dust and streaks scatter light, so keep windows, mirrors, and lamps clear.',
        'Watch for what has no light: pedestrians, animals, debris, and parked cars may appear late. Scan the edges.',
      ]),
      remember('Night rule', [
        'When you can see less, slow down. Give yourself more time and more space.',
        'Low visibility and poor traction shrink the time available to solve a problem.',
        'The cure is not a brighter or faster response; it is a calmer one — see what you can, stay within that distance, and leave more room.',
      ]),
    ],
    test: [
      q('What are headlights for besides illuminating the road?', ['Granting right-of-way', 'Making your vehicle easier to detect', 'Changing the speed limit'], 1, 'Required lighting also helps other road users detect your vehicle.', { image: 'night-weather-visibility-a01' }),
      q('When following another vehicle in {{state}}, within what distance must high beams be dimmed?', ['Within {{highBeam.followingFeet}} feet', 'Within {{highBeam.approachingFeet}} feet', 'Only when the other driver flashes'], 0, 'The following-distance dimming rule is {{highBeam.followingFeet}} feet; the approaching-vehicle distance is {{highBeam.approachingFeet}} feet.', { image: 'night-weather-visibility-a02' }),
      q('When should you switch from high beams for an approaching car?', ['Within {{highBeam.approachingFeet}} feet', 'Only when it is closer than a car length', 'Only after it flashes'], 0, '{{state}} requires dimming within {{highBeam.approachingFeet}} feet of an approaching vehicle.'),
      q('What should you do when oncoming headlights create glare?', ['Look directly at them', 'Use the right road edge as a guide', 'Close one eye'], 1, 'Look toward the right edge and reduce speed without staring at the lights.'),
      q('Your headlights show less road than you need to stop. What should you do?', ['Slow down', 'Use parking lights', 'Drive faster'], 0, 'Your speed must let you stop within the road you can see.'),
      q('Why clean headlights and windows before a night drive?', ['To improve visibility', 'To save fuel', 'To reduce tire wear'], 0, 'Clean glass and lights help you see and be seen.'),
    ],
  }),

  lesson('weather-and-mountain-roads', {
    title: 'Rain, Fog, Heat, and Mountain Roads',
    objective: 'Bad conditions reduce the grip and visibility you normally trust.',
    keyPoints: ['Slow before traction disappears.', 'Use low beams in fog.', 'Plan space on narrow grades.'],
    challenge: challenge(
      'Heavy fog reflects your high beams back at you.',
      'Which lights should you use?',
      ['Low beams', 'High beams', 'Parking lights only'],
      0,
      'Low beams reduce glare and light the road more effectively.',
      { image: 'weather-and-mountain-roads-ca-night-weather-visibility-a01' },
    ),
    cards: [
      rule('Rain changes two things', [
        'Rain reduces visibility as well as tire grip.',
        'The first minutes of rain are the slickest, because oil and dust float on the surface.',
        'Bridges and overpasses ice over before the road around them. Shaded patches freeze first and dry out last.',
        'After deep water, brakes can go soft. Dry them by pressing brake and accelerator lightly at the same time.',
      ]),
      recall('Recall · Rain', 'Rain cuts [[grip]] and [[visibility]] — slow down and smooth every control.'),
      rule('Make every control smoother', [
        'Rain, snow, wind, standing water, or a loose surface calls for reduced speed, more following space, and smooth steering, braking, and acceleration.',
        'If hydroplaning begins, ease off the accelerator and avoid abrupt braking or steering that can turn reduced grip into a skid.',
        'In poor conditions, make these three changes:',
      ], { bullets: ['Brake earlier.', 'Turn gently.', 'Leave a larger following gap.'] }),
      recall('Recall · Ice and wet brakes', 'Bridges and overpasses ice over [[first]]. Dry wet brakes with [[light]] presses on brake and gas.'),
      image('weather-and-mountain-roads-ca-night-weather-visibility-a02'),
      rule('Fog needs low beams', [
        'High beams reflect light back. Use low beams and reduce speed.',
        'If the fog is too thick to drive safely, leave the road at a safe place and wait.',
        'Never drive into unknown water. Depth and current are hard to judge, so turn around when the road is flooded.',
        'Heat can hurt the vehicle. Watch tires, temperature, and warning lights.',
        'Never leave a child or a pet in a parked car.',
      ]),
      recall('Recall · Fog', 'In fog, use [[low]] beams — high beams reflect back and reduce what you see.'),
      rule('Wind moves more than your car', [
        'Expect trucks, trailers, bicycles, and debris to shift. Hold space on both sides.',
        'Narrow mountain roads need cooperation. When cars cannot pass, the driver with the easier retreat backs up, usually the one facing downhill.',
        'Use the nearest safe turnout rather than squeezing past.',
        'Downhill, use a lower gear so the brakes do not overheat.',
      ]),
      image('weather-and-mountain-roads-ca-night-weather-visibility-a03'),
      remember('Conditions set the pace', [
        'If you cannot see or grip enough road, slow down or stop somewhere safe.',
        'Never drive faster than is reasonable for darkness, fog, smoke, rain, glare, or traffic.',
        'Keep stopping distance within the visible usable path.',
        'The exam rewards the driver who changes speed before the road forces the change, not after the first slide.',
      ]),
    ],
    test: [
      q('Which response is best?', ['Follow the taillights ahead closely', 'Use low beams, slow down, and increase space', 'Use high beams and maintain speed'], 1, 'Reduced visibility calls for low beams, lower speed, and more stopping space.', { image: 'weather-and-mountain-roads-ca-night-weather-visibility-a01' }),
      q('Your stopping distance is longer than the road you can see. What should you do?', ['Drive closer to another vehicle', 'Slow until you can stop within the visible path', 'Use high beams and continue'], 1, 'Speed must fit the usable visible stopping distance.', { image: 'weather-and-mountain-roads-ca-night-weather-visibility-a03' }),
      q('What control style is safest when traction is reduced?', ['Frequent hard braking', 'Smooth and progressive', 'Abrupt and aggressive'], 1, 'Smooth inputs preserve the limited tire grip available.', { image: 'weather-and-mountain-roads-ca-night-weather-visibility-a03' }),
      q('Which headlights should you normally use in fog or smoke?', ['High beams', 'Low beams', 'Parking lights only'], 1, 'Low beams reduce reflected glare and help you see the roadway better in fog or smoke.'),
      q('Which part of the road freezes first in cold weather?', ['Bridges and overpasses', 'The middle of a sunny straight', 'Freshly paved sections'], 0, 'Bridges and overpasses lose heat from both sides and ice over before the road around them.'),
      q('Two cars meet on a steep narrow road and cannot pass. Who normally backs up?', ['The driver facing downhill', 'The driver facing uphill', 'The larger car'], 0, 'The downhill-facing driver can usually reverse uphill under better control, so that driver backs up to a safe place.'),
    ],
  }),

  lesson('skids-and-emergencies', {
    title: 'Skids, Blowouts, and Vehicle Failure',
    objective: 'Smooth control matters most when the vehicle stops behaving normally.',
    keyPoints: ['Avoid sudden inputs.', 'Look toward the safe path.', 'Move people away from greater danger.'],
    challenge: challenge(
      'A front tire suddenly blows out.',
      'What should you do first?',
      ['Brake hard', 'Hold the wheel and ease off', 'Turn sharply'],
      1,
      'Keep the car stable before moving toward the roadside.',
      { image: 'skids-and-emergencies-a01' },
    ),
    cards: [
      why('A blowout needs calm hands', [
        'Grip the wheel firmly. Keep the car pointed where you want to go.',
        'Emergency questions often offer a dramatic action that feels decisive.',
        'The safer answer usually stabilizes first and avoids adding a second failure through panic steering or braking.',
      ]),
      rule('Do not slam the brakes', [
        'Ease off the accelerator. Slow gradually before leaving the road.',
        'The first seconds are about keeping the vehicle stable.',
        'Hold the steering wheel firmly and keep the vehicle pointed straight.',
        'Slow gradually, signal, and move off the roadway when safe.',
      ]),
      recall('Recall · Blowout', 'Blowout? [[Grip]] the wheel, ease off the gas, and do not [[slam]] the brakes.'),
      image('skids-and-emergencies-a02'),
      visual('A skid means lost grip', [
        'Look toward the safe path. Ease off the cause and steer smoothly.',
        'When traction is lost, avoid sudden braking, acceleration, or steering.',
        'Look toward the intended path and recover control progressively.',
        'A large correction can send the tires past available grip in the opposite direction.',
      ]),
      recall('Recall · Skid response', 'In a skid, ease off the cause, look toward your intended [[path]], and steer [[smoothly]].'),
      related('Different skids need different corrections', [
        'Avoid one memorized steering slogan. Use the vehicle handbook and modern stability systems correctly.',
        'With anti-lock brakes, press firmly and hold; without them, ease off and reapply so the wheels keep rolling.',
        'Mechanical failures feel different, but the first priority is the same: keep the vehicle stable, communicate, reduce exposure, and stop in the safest place.',
      ]),
      visual('Off the pavement? Slow first', [
        'Hold the wheel steady. Return at a shallow angle only when speed and traffic allow.',
        'A fast steering correction can turn a small drift into a loss of control.',
        'Ease off the accelerator and hold the wheel firmly. Brake gently if needed while keeping the vehicle straight.',
      ]),
      image('skids-and-emergencies-a03'),
      related('Brake failure needs options', [
        'Try controlled braking, a lower gear, and the parking brake gradually. Look for a safe escape path.',
        'Keep control first, alert others, and identify a safe escape.',
        'The exact vehicle-specific action can differ, so use the owner manual for equipment details.',
      ]),
      rule('A roadside stop is still dangerous', [
        'Pull fully away from traffic. Use hazards and stay protected when possible.',
        'When a collision threat develops, reduce speed and choose the path that preserves control while protecting people.',
        'An empty shoulder may be better than a crowded lane. A controlled impact may be better than a violent swerve into pedestrians or opposing traffic.',
      ]),
      remember('Emergency order', [
        'Hold the steering wheel securely, avoid a panic brake, and reduce accelerator pressure progressively.',
        'Correct only enough to stabilize the vehicle.',
        'Once control and speed allow, signal and move to the safest available place away from traffic.',
        'When the vehicle fails, keep this order:',
      ], { bullets: ['Control the car.', 'Reduce speed.', 'Choose the safest place.', 'Call for help.'] }),
    ],
    test: [
      q('What should you prioritize?', ['Hold control, ease off gradually, and move out of traffic when stable', 'Brake and steer sharply', 'Turn off the ignition immediately'], 0, 'During a failure, preserve control before attempting a large speed or direction change.', { image: 'skids-and-emergencies-a01' }),
      q('Where should you look during a skid recovery?', ['At the obstacle only', 'At the rear seat', 'Toward the intended safe path'], 2, 'Looking and steering toward the intended path supports a progressive recovery.', { image: 'skids-and-emergencies-a01' }),
      q('Why avoid hard braking immediately after a tire failure?', ['It inflates the tire', 'It turns on high beams', 'It can worsen instability'], 2, 'Abrupt braking can increase the pull or loss of control.', { image: 'skids-and-emergencies-a02' }),
      q('What is the first universal priority in a vehicle failure?', ['Maintain vehicle control', 'Call a mechanic while moving', 'Leave the vehicle immediately'], 0, 'Control comes before communication, escape, and stopping.', { image: 'skids-and-emergencies-a03' }),
      q('What guides the last-second escape choice?', ['Protecting paint at any cost', 'Following the fastest vehicle', 'Protecting people while preserving control'], 2, 'The safest available path minimizes human harm without sacrificing control.', { image: 'skids-and-emergencies-a03' }),
      q('A front tire suddenly blows out. What should you do first?', ['Brake as hard as possible', 'Hold the wheel firmly and ease off the accelerator', 'Turn sharply toward the shoulder'], 1, 'Keep control with a firm grip and smooth deceleration before moving off the roadway.'),
    ],
  }),

  lesson('crashes-and-insurance', {
    title: 'After a Crash',
    objective: 'Protect people first. Reports and insurance come after immediate safety.',
    keyPoints: ['Stop and protect the scene.', 'Exchange required information.', 'Complete every required report.'],
    challenge: challenge(
      'A crash causes an injury.',
      'What is the first priority?',
      ['Leave before traffic builds', 'Stop and get help', 'Call the insurance company first'],
      1,
      'Stop, protect people, and arrange emergency help.',
      { image: 'crashes-and-insurance-a01' },
    ),
    cards: [
      rule('Stop after a collision', [
        'Do not leave the scene. Move out of traffic when the law and safety allow.',
        'A collision scene can create a second crash.',
        'Call emergency services for injuries or immediate danger.',
        'Move vehicles only when safe and appropriate, and warn approaching traffic when possible.',
      ]),
      rule('Check people before property', [
        'Call 911 for injury or immediate danger. Give reasonable help without creating another hazard.',
        'A collision creates several separate duties: protect people, stop, provide information, give aid, and make the correct later reports.',
        'Police, {{agency}}, and insurance steps are not interchangeable.',
      ]),
      recall('Recall · After a crash', 'Stop, check [[people]] first, exchange [[information]] — never leave the scene.'),
      rule('Exchange the required information', [
        'Share your name, address, license, vehicle registration, and insurance details. Stay calm and factual.',
        'After an injury or fatal crash, stop, share the required information, and give reasonable help.',
        'Arrange medical transportation when needed or requested.',
        'Do not argue about fault at the roadside; note the facts, the other driver’s details, and any witnesses.',
      ]),
      rule('An unattended car still creates duties', [
        'If you hit a parked car or other property and the owner cannot be found, leave a written notice with your name, address, and an explanation.',
        'Then notify the police as your state directs.',
        'Leaving because the damage looks small can turn a crash into a failure-to-stop offense.',
      ]),
      rule('Reports have triggers', [
        'Report a crash to law enforcement when the law requires it: an injury, a death, or significant property damage.',
        'In {{state}}, a crash with injury, death, or {{crash.reportDamagePhrase}} must be reported.',
        'A report someone else makes does not always satisfy your own duty. Check every trigger.',
      ]),
      recall('Recall · Reporting', 'A crash with [[injury]], death, or serious damage must be [[reported]] — never leave the scene.'),
      rule('Insurance follows its own process', [
        'Document the scene when safe. Notify the insurer and keep records.',
        'Drivers and owners must be able to prove financial responsibility at all times, and show it to an officer on request.',
        'In {{state}}, the minimum liability limits are ${{insurance.perPerson}} for one person’s injury or death, ${{insurance.perCrash}} for two or more, and ${{insurance.property}} for property damage.',
      ]),
      recall('Recall · Insurance', 'Minimum liability limits: [[${{insurance.perPerson}}]] per person, [[${{insurance.perCrash}}]] per crash, and ${{insurance.property}} for property.'),
      remember('Remember the order', [
        'A driver who cannot prove financial responsibility after a reportable crash can lose the license.',
        'Exam questions mix up the steps on purpose: the insurer call is never the first move, and a small dent never cancels the duty to stop.',
        'After a collision, keep these actions in order:',
      ], { bullets: ['Stop.', 'Protect.', 'Help.', 'Exchange.', 'Report.'] }),
    ],
    test: [
      q('What must the driver do?', ['Wait only for an insurance agent', 'Stop, leave the required written information, and notify police as required', 'Leave because no one is injured'], 1, 'Property-damage duties still require stopping and providing information or the legal notice and police notification.', { image: 'crashes-and-insurance-a01' }),
      q('What is the minimum property-damage liability coverage in {{state}}?', ['${{insurance.property}}', '${{insurance.perPerson}}', '${{insurance.perCrash}}'], 0, 'In {{state}} the property-damage minimum is ${{insurance.property}}; the other two figures are the injury limits.', { image: 'crashes-and-insurance-a01' }),
      q('The damaged property’s owner is absent. Is leaving a note alone always enough?', ['Only if the damage is large', 'No, also follow the required police-notification duty', 'Yes'], 1, 'The law requires the written notice and the police notification when the owner cannot be found.'),
      q('Which duty comes first at a crash scene?', ['Photographing the damage', 'Protecting people and getting help', 'Calling the insurer'], 1, 'Safety and aid come before information exchange, reports, and insurance.'),
      q('A crash in {{state}} causes {{crash.reportDamagePhrase}} and no injuries. Must it be reported?', ['Yes, that damage makes it reportable', 'No, only injuries are reportable', 'Only if the other driver asks'], 0, 'In {{state}}, {{crash.reportDamagePhrase}} is a reporting trigger, like injury or death.'),
      q('Does telling your insurance company replace the report the law requires?', ['Yes, in every case', 'No, the legal reporting duty can be separate', 'Only when both vehicles are insured'], 1, 'Insurance notification is a separate process from the police or state report the law requires.'),
    ],
  }),
];
