// Module 2 · Read the Road — universal skeleton.
import {
  lesson,
  why,
  rule,
  related,
  remember,
  trap,
  visual,
  image,
  recall,
  challenge,
  q,
} from '../helpers.mjs';

export const LESSONS = [
  lesson('sign-shapes-and-colors', {
    title: 'Sign Shapes Give You a Head Start',
    objective: 'A sign can warn you before every word becomes readable.',
    keyPoints: ['Use shape first.', 'Use color as a clue.', 'Read the exact message.'],
    challenge: challenge(
      'You see a red eight-sided sign ahead.',
      'What should you expect?',
      ['A warning', 'A full stop', 'A guide sign'],
      1,
      'The octagon is reserved for STOP.',
      { image: 'sign-shapes-and-colors-a01' },
    ),
    cards: [
      why('Start with the family', [
        'Shape and color give you an early clue. They help before the details are clear.',
        'Regulatory signs tell road users what is required or prohibited.',
        'Warning signs call attention to a condition that may demand an early adjustment.',
        'Guide signs help with routes, destinations, and services.',
        'This first classification narrows the meaning before you read the details.',
      ]),
      rule('The octagon means STOP', [
        'Eight sides have one traffic meaning. Prepare for a complete stop.',
        'Traffic signs are designed to work at a glance. You do not need to memorize every sign as an isolated picture.',
        'First identify its family, then read the symbol or words, and finally connect it to the decision you must make.',
      ]),
      image('sign-shapes-and-colors-a02'),
      visual('The downward triangle means YIELD', [
        'Slow down and scan for conflicts. Stop if someone needs the space.',
        'Some shapes are deliberately unique. An octagon identifies STOP; a downward-pointing triangle identifies YIELD.',
        'A pennant warns of a no-passing zone, and a pentagon marks a school-related area.',
        'Recognizing these silhouettes buys time when visibility is poor or the sign is partly blocked.',
      ]),
      recall('Recall · Shapes', 'The eight-sided octagon always means [[STOP]]. The downward triangle always means [[YIELD]].'),
      related('The round sign warns about tracks', [
        'A railroad crossing is ahead. Look for gates, lights, and a clear exit.',
        'A sign is easier to read when you do not treat it as one big picture.',
        'First: identify the family from shape and color. Second: read the symbol, words, arrow, or plaque.',
        'Third: turn the message into an action you can take now.',
      ]),
      recall('Recall · Round sign', 'A [[round]] sign warns that [[railroad]] tracks are ahead.'),
      visual('The pentagon marks a school area', [
        'Expect children near the road. Slow down and scan the sidewalks.',
        'Do not treat color as the complete answer. Two signs may share a color but require very different actions.',
        'On an exam, identify the family quickly, then use the symbol, wording, placement, and any plaque to choose the exact response.',
      ]),
      image('sign-shapes-and-colors-a03'),
      rule('A diamond warns', [
        'The symbol shows the type of hazard you are approaching.',
        'Change your speed or position early, while you still have room.',
        'Shape and color help you predict the message, but the words, symbol, plaque, lane position, and operating times determine the real instruction.',
        'A sign mounted over one lane may apply only to that lane. A time plaque can make a restriction active only during stated hours.',
      ]),
      trap('Colors support the message', [
        'Red is strongly associated with stopping or prohibition. Yellow calls attention to general warnings.',
        'Orange is used for temporary traffic control and work activity. Green, blue, and brown commonly guide rather than command.',
        'Color is a clue, not permission to ignore the actual symbol, words, or roadway context.',
        'Use these color families as quick clues:',
      ], { bullets: ['Red often restricts.', 'Yellow warns.', 'Orange marks work zones.', 'Green guides.'] }),
      recall('Recall · Colors', '[[Red]] restricts. [[Yellow]] warns. [[Orange]] means work zones.'),
      remember('The exact message wins', [
        'Shape and color help you identify the sign before you read every detail.',
        'Words, symbols, arrows, and plaques give the full rule.',
        'A plaque may limit a rule to certain hours or vehicles. An overhead sign may control only the lane below it.',
        'Road conditions and an officer’s directions can change what you do next.',
      ]),
    ],
    test: [
      q('What should you expect from this sign?', ['A parking permission', 'A destination or route number', 'A warning about a condition ahead'], 2, 'A yellow diamond is used for a warning, so begin looking for the condition it describes.', { image: 'sign-shapes-and-colors-q01-a' }),
      q('Which sign family normally tells you that a movement is prohibited?', ['Warning', 'Guide', 'Regulatory'], 2, 'A prohibition is a regulatory instruction.', { image: 'sign-shapes-and-colors-q02-a' }),
      q('A sign has a downward-pointing triangular shape. What control should you expect?', ['Stop', 'School area', 'Yield'], 2, 'The distinctive downward triangle identifies YIELD.', { image: 'sign-shapes-and-colors-q03-a' }),
      q('Which color most strongly suggests a temporary work-zone condition?', ['Green', 'Brown', 'Orange'], 2, 'Orange is the standard temporary traffic-control color family.', { image: 'sign-shapes-and-colors-q04-a' }),
      q('A lane-use sign is mounted directly over the left lane. Which traffic should apply it first?', ['Drivers in every lane equally', 'Only pedestrians', 'Drivers in the left lane'], 2, 'An overhead lane-use sign normally applies to the lane beneath it.', { image: 'sign-shapes-and-colors-q05-a' }),
      q('You recognize a sign’s color but cannot yet see its symbol. What is the best next step?', ['Treat the color as the complete instruction', 'Use the color to identify the family, then read the exact message', 'Ignore the sign until you are beside it'], 1, 'Color is an early clue. The symbol, words, placement, and plaques give the exact instruction.'),
    ],
  }),

  lesson('regulatory-signs', {
    title: 'Signs That Tell You What to Do',
    objective: 'Regulatory signs control a specific action, lane, vehicle, or time.',
    keyPoints: ['Read signs as actions.', 'Check every plaque.', 'Follow authorized directions.'],
    challenge: challenge(
      'A police officer waves you through a red light.',
      'What should you follow?',
      ['The red light only', 'The officer’s direction', 'The car beside you'],
      1,
      'Follow the authorized direction while checking that the path is safe.',
      { image: 'regulatory-signs-a01' },
    ),
    cards: [
      why('Read the sign as a verb', [
        'The fastest exam strategy is to ask which action the sign controls.',
        'STOP means make a complete stop at the lawful stopping point. YIELD means give way and stop if needed.',
        'Turn, entry, speed, lane-use, and parking signs control a specific choice.',
        'Start by naming the action:',
      ], { bullets: ['Stop.', 'Yield.', 'Turn.', 'Enter.', 'Park.'] }),
      rule('White rectangles give exact rules', [
        'They often control speed, turns, parking, or lane use. Read the full message.',
        'STOP requires a complete stop at the lawful stopping point before you evaluate the path.',
        'YIELD requires you to slow enough to give way and stop when necessary.',
        'In both cases, proceed only after the conflicting path is clear. The difference is whether a stop is always required.',
      ]),
      image('regulatory-signs-a02'),
      visual('A red slash means no', [
        'The symbol shows the prohibited move. Do not perform that action.',
        'A regulatory sign does not grant right-of-way simply because you obeyed it.',
        'After stopping or following a lane instruction, you still must yield to traffic or pedestrians lawfully in the conflict area.',
      ]),
      recall('Recall · Red slash', 'A red circle with a slash means that movement is [[not allowed]].'),
      rule('DO NOT ENTER protects one direction', [
        'The road or ramp is closed to your movement. Choose another legal path.',
        'You must obey a traffic sign or signal that applies to you unless an authorized officer directs otherwise or a legal exception applies.',
        'Follow an officer who directs you through a red light.',
        'Keep watching for people and drivers who may not expect the temporary traffic pattern.',
      ]),
      recall('Recall · One direction', 'DO NOT ENTER protects [[one direction]] of traffic — WRONG WAY means you are already against it.'),
      visual('WRONG WAY means act now', [
        'Slow down. Move out of opposing traffic without creating another hazard.',
        'DO NOT ENTER protects the entrance; WRONG WAY warns that you are facing traffic moving toward you.',
        'Do not continue deeper into the roadway.',
        'Slow, stop in the safest available position, and reverse direction only when you can do so without creating another conflict.',
      ]),
      image('regulatory-signs-a03'),
      related('Plaques narrow the rule', [
        'A rule may apply only at certain times. It may target one lane or one vehicle type.',
        'Turn-prohibition, one-way, lane-use, speed, entry, and parking signs regulate a particular choice.',
        'Read the arrow, the vehicle symbol, the lane placement, and the plaque.',
        'A NO LEFT TURN sign does not prohibit going straight, and a carpool-lane sign does not apply outside its posted conditions.',
      ]),
      rule('People can direct traffic', [
        'An authorized officer or flagger may override the normal pattern. Move carefully.',
        'Traffic may be directed differently during an emergency, a collision, or a special operation.',
        'Follow a police officer or another person legally authorized to direct traffic.',
        'Do not assume obeying a signal gives you the right-of-way over someone already in danger.',
      ]),
      remember('Exam shortcut', [
        'Find the controlled action first. Then check lane, time, vehicle, and exception.',
        'Regulatory signs turn road design into clear instructions.',
        'The useful exam skill is not simply naming the sign.',
        'It is identifying the controlled movement, lane, vehicle, time, or place and acting before you enter the restricted area.',
      ]),
    ],
    test: [
      q('What is the correct response?', ['Enter slowly if no vehicle is visible', 'Stop on the ramp and wait for permission', 'Take the open branch'], 2, 'A regulatory prohibition must be obeyed; choose the lawful route instead.', { image: 'regulatory-signs-q01-a' }),
      q('Which control always requires a complete stop?', ['YIELD', 'Advisory speed', 'STOP'], 2, 'STOP always requires a complete stop; YIELD may not when no stop is needed to give way.', { image: 'regulatory-signs-q02-a' }),
      q('A NO U-TURN sign is posted at an intersection. Which movement is prohibited?', ['Driving straight', 'A U-turn', 'Every leftward movement'], 1, 'The pictured or stated U-turn is the prohibited movement.', { image: 'regulatory-signs-q03-a' }),
      q('You realize you entered a one-way road against traffic. What is the priority?', ['Stop worsening the exposure and leave safely', 'Accelerate to the next intersection', 'Use the shoulder as a travel lane'], 0, 'The safe response is to stop increasing the wrong-way exposure and exit only when safe.', { image: 'regulatory-signs-q04-a' }),
      q('An officer directs you through a red light. Which instruction controls?', ['The driver behind you', 'The officer’s direction', 'The red light with no exception'], 1, 'An authorized officer’s active direction controls the temporary movement.', { image: 'regulatory-signs-q05-a' }),
      q('A police officer waves you through an intersection while your signal is red. What should you do?', ['Wait for green in every case', 'Follow the officer’s direction while checking that the path is safe', 'Reverse away from the intersection'], 1, 'An authorized traffic direction takes priority over the ordinary signal, but you must still move carefully.'),
    ],
  }),

  lesson('warning-and-guide-signs', {
    title: 'Signs That Warn You Early',
    objective: 'A warning sign gives you time. Use that time before the hazard.',
    keyPoints: ['Read the symbol.', 'Adjust before the hazard.', 'Use guide signs without sudden moves.'],
    challenge: challenge(
      'A LANE ENDS sign appears ahead.',
      'What should you do first?',
      ['Wait for the lane to disappear', 'Check traffic and plan a merge', 'Stop in your lane'],
      1,
      'Plan early. A small speed change is better than a last-second move.',
      { image: 'warning-and-guide-signs-a01' },
    ),
    cards: [
      why('Warnings buy you time', [
        'Look farther ahead. Prepare before the road changes.',
        'A warning sign does not tell you one fixed speed or maneuver. It gives you time to prepare.',
        'Adjust speed and lane position before the hazard.',
        'Expect the risk to be hidden around a curve, a hill, a work area, or a crossing.',
      ]),
      rule('The symbol names the problem', [
        'Curves, merges, crossings, and slippery roads use clear symbols. Match your action to the hazard.',
        'Curve, crossroad, merging, divided-highway, lane-ending, slippery-surface, and signal-ahead signs preview the road or the traffic pattern.',
        'Identify the hazard, check the surrounding traffic, and make the smallest early speed or lane adjustment that preserves control.',
      ]),
      image('warning-and-guide-signs-a02'),
      rule('Advisory speed is about the hazard', [
        'A yellow plaque under a warning sign suggests a safer speed for the condition ahead.',
        'It is not the general speed limit, and it assumes good conditions.',
        'In rain or darkness the safe speed through the curve may be lower than the plaque.',
        'Braking hard inside a curve can send you off the road; slow before you enter it.',
      ]),
      recall('Recall · Advisory speed', 'A yellow advisory speed describes the [[hazard]] — it is not a separate legal limit.'),
      related('School signs widen your scan', [
        'Watch sidewalks, parked cars, and crosswalks. A child may appear from the side.',
        'A school-area pentagon or a pedestrian warning shifts your attention beyond vehicle traffic.',
        'Look toward sidewalks, parked cars, crossing points, and people who may enter the roadway.',
        'The sign warns of the environment; any posted speed or crossing control supplies the exact legal instruction.',
      ]),
      rule('Railroad warnings need an exit plan', [
        'Never enter tracks without room beyond them. A train cannot steer around you.',
        'Railroad advance signs tell you to look, listen, and prepare for crossing controls.',
        'Never begin across tracks unless space on the far side can hold the entire vehicle.',
        'Entering behind another vehicle can trap you even when the warning equipment was clear at first.',
      ]),
      image('warning-and-guide-signs-a03'),
      rule('Orange means temporary work', [
        'Slow down. Expect workers, equipment, closed lanes, and flaggers.',
        'Work-zone signs, cones, drums, barriers, arrow boards, and flaggers can replace the normal path.',
        'Reduce speed for the actual conditions, increase space, and follow the temporary channel.',
        'Green, blue, and brown guide signs support navigation; read them early so you do not cut across traffic.',
      ]),
      recall('Recall · Orange signs', '[[Orange]] warning signs mean a [[temporary]] work zone ahead.'),
      trap('Guide signs help you plan', [
        'Warning and special-area signs are advance information.',
        'They let you trade a sudden reaction for an early, controlled adjustment.',
        'Guide signs serve a different purpose: they help you choose a route or service without a last-second lane change.',
        'The color gives you a quick clue:',
      ], { bullets: ['Green shows routes and destinations.', 'Blue often shows services.', 'Brown points to recreation.'] }),
      remember('Missed the sign?', [
        'Continue safely. Do not make a sudden turn or reverse to recover the route.',
        'A warning sign does not automatically set right-of-way or a universal speed. It tells you what to expect.',
        'Apply any posted regulation, then choose a speed that is safe for the actual sight distance, surface, traffic, and people present.',
      ]),
    ],
    test: [
      q('What should you do first?', ['Scan ahead and adjust before the curve', 'Wait until the car begins to slide', 'Move across the centerline for a wider path'], 0, 'A warning gives advance time to see the hazard and adjust early.', { image: 'warning-and-guide-signs-q01-a' }),
      q('A LANE ENDS warning appears. What is the useful response?', ['Stop immediately in the lane', 'Speed past every nearby vehicle', 'Check traffic and plan a safe merge early'], 2, 'The sign gives advance notice so you can locate a gap and merge safely.', { image: 'warning-and-guide-signs-q02-a' }),
      q('After a school warning sign, where should your scan expand?', ['Only the centerline', 'Only the rearview mirror', 'Sidewalks and crossing areas'], 2, 'Children and pedestrians can enter from the sides, so scan the full roadside environment.', { image: 'warning-and-guide-signs-q03-a' }),
      q('Traffic is stopped just beyond the tracks. What should you do?', ['Drive around the lowered gate', 'Wait before the tracks until enough space opens', 'Follow the car ahead onto the tracks'], 1, 'Do not enter tracks without enough room to clear them completely.', { image: 'warning-and-guide-signs-q04-a' }),
      q('A flagger directs traffic through a temporary lane. What should you follow?', ['The flagger and temporary controls', 'The faded permanent line only', 'The route chosen by the car behind'], 0, 'Authorized temporary controls define the safe work-zone path.', { image: 'warning-and-guide-signs-q05-a' }),
      q('Traffic is stopped just beyond railroad tracks. When may you enter the crossing?', ['As soon as the vehicle ahead begins moving', 'Only when there is enough room to clear the tracks completely', 'Whenever no train is visible'], 1, 'You need a clear space beyond the tracks before entering, even when no train is currently visible.'),
    ],
  }),

  lesson('road-markings-and-curbs', {
    title: 'Lines, Arrows, and Stop Lines',
    objective: 'The road surface tells you where to drive, stop, and turn.',
    keyPoints: ['Read color and pattern.', 'Follow lane arrows.', 'Use the correct stopping point.'],
    challenge: challenge(
      'A stop sign has a painted stop line.',
      'Where should you stop first?',
      ['Before the line', 'Across the crosswalk', 'Beside the sign'],
      0,
      'The stop line is the first stopping point.',
      { image: 'road-markings-and-curbs-a01' },
    ),
    cards: [
      why('Color tells you the traffic relationship', [
        'Yellow lines separate traffic moving in opposite directions or mark the left edge of a divided road.',
        'White lines separate lanes moving in the same direction and mark the right edge.',
        'Start with color before interpreting broken, solid, or double patterns.',
      ]),
      recall('Recall · Line colors', '[[Yellow]] lines separate opposite directions. [[White]] lines separate lanes going the same way.'),
      rule('Pattern tells you about crossing', [
        'Broken lines may allow crossing when the maneuver is otherwise legal and safe.',
        'A solid line warns against crossing or restricts it.',
        'Double solid white lines form a lane barrier: wait for a permitted opening or a broken pattern instead of forcing a lane change.',
      ]),
      recall('Recall · Line patterns', 'A [[broken]] line allows crossing when safe. A [[solid]] line restricts it.'),
      image('road-markings-and-curbs-a02'),
      rule('Double lines need attention', [
        'Do not treat every double line the same. Color, spacing, and road context matter.',
        'Double solid yellow lines bar passing across the center. A limited turn into a driveway may still be allowed where another rule permits it.',
        'A broken yellow line on your side means you may pass when it is clear; a solid yellow on your side means you may not.',
        'Do not answer a marking question from color alone: pattern, arrows, signs, and roadway context determine the permitted movement.',
      ]),
      related('Arrows assign a movement', [
        'Choose the lane before the last moment. Follow the arrow painted in your lane.',
        'Road markings are a language under your tires.',
        'Color identifies the relationship between traffic streams; pattern shows whether crossing is permitted; arrows and painted areas organize where movements belong.',
      ]),
      rule('Stop lines show where to stop', [
        'Stop lines and crosswalk markings show where the front of your vehicle should stop.',
        'Stop before the stop line when one is present. Without a line, stop before the crosswalk.',
        'Keep crosswalks clear.',
        'Move forward only as needed for visibility after the required stop and after yielding.',
      ]),
      image('road-markings-and-curbs-a03'),
      related('Painted islands are not travel lanes', [
        'Stay out unless markings allow entry. Do not use them to pass a queue.',
        'Diagonal stripes and wide painted medians separate traffic streams or protect a turning area.',
        'Do not drive on or across them. Use only a marked opening or another legally allowed path.',
      ]),
      rule('Curbs and signs control stopping', [
        'Painted curbs and posted signs tell you where stopping and parking are allowed.',
        'Curb colors and their meanings are set by the state or the city, so read the sign beside the paint.',
        'When paint and sign seem to disagree, the sign gives the exact rule.',
        'A hydrant, a bus zone, or a driveway keeps its restriction even where the curb is unpainted.',
      ]),
      remember('Read markings in layers', [
        'One marking rarely tells the whole story.',
        'Color tells you whether traffic usually moves in the same or opposite directions. Broken or solid patterns show where crossing is permitted.',
        'Arrows and words assign movements to particular lanes.',
        'Read the road surface in this order:',
      ], { bullets: ['Color first.', 'Then pattern.', 'Then arrows, signs, and nearby traffic.'] }),
    ],
    test: [
      q('What does the changing pattern tell you?', ['Passing permission is ending; evaluate and finish only if safe', 'Traffic now moves in the same direction', 'The shoulder becomes a travel lane'], 0, 'Yellow separates opposing traffic, and the solid pattern restricts crossing for passing.', { image: 'road-markings-and-curbs-q01-a' }),
      q('Which color normally separates opposing traffic?', ['White', 'Blue', 'Yellow'], 2, 'Yellow normally separates opposing directions.', { image: 'road-markings-and-curbs-q02-a' }),
      q('You reach double solid white lines beside a carpool lane. What should you do?', ['Cross whenever traffic is light', 'Stop in your lane', 'Wait for a designated opening'], 2, 'Double solid white lines form a barrier; use a designated entry or exit.', { image: 'road-markings-and-curbs-q03-a' }),
      q('A wide painted median with diagonal stripes separates the two directions. What does it mean?', ['A regular passing lane', 'A bicycle lane', 'A barrier you must not drive on or across'], 2, 'A striped painted median separates traffic streams; use only a marked opening.', { image: 'road-markings-and-curbs-q04-a' }),
      q('The curb is painted and a sign beside it lists hours. Which one gives the exact stopping rule?', ['The paint alone', 'The sign, read together with the paint', 'Neither; you may stop anywhere'], 1, 'Painted curbs signal a restriction, but the posted sign gives the exact rule and hours.', { image: 'road-markings-and-curbs-q05-a' }),
      q('At a stop sign with a marked stop line, where should your vehicle first stop?', ['Past the crosswalk', 'Before the stop line', 'Beside the stop sign'], 1, 'The marked stop line is the first lawful stopping point.'),
    ],
  }),
];
