// Module 3 · Intersections and Everyday Moves — universal skeleton.
import {
  lesson,
  why,
  rule,
  related,
  remember,
  trap,
  visual,
  image,
  recall,
  challenge,
  q,
} from '../helpers.mjs';

export const LESSONS = [
  lesson('uncontrolled-intersections', {
    title: 'Who Goes First?',
    objective: 'Right-of-way rules organize movement. They do not remove danger.',
    keyPoints: ['Check who arrived first.', 'Look right when arrival is tied.', 'Never force a turn.'],
    challenge: challenge(
      'Two cars reach an uncontrolled intersection together.',
      'Which car normally goes first?',
      ['The car on the right', 'The car on the left', 'The faster car'],
      0,
      'When arrival is tied, the car on the right normally goes first.',
      { image: 'uncontrolled-intersections-a01' },
    ),
    cards: [
      rule('Someone already inside goes first', [
        'Let the intersection clear. Do not challenge a vehicle already in your path.',
        'If another vehicle is already inside the intersection, let it clear before you enter.',
        'Do not use your speed or your arrival story to challenge someone who is physically in the conflict area.',
        'Slow early and keep an escape option.',
      ]),
      rule('Arrival order organizes the queue', [
        'The first clear arrival normally moves first. A driver who arrives later waits for the earlier vehicle.',
        'When one road user clearly arrives first, that person proceeds first after checking the intersection.',
        'The useful clue is not which vehicle is larger or faster. It is the order in which each reaches the decision point.',
      ]),
      image('uncontrolled-intersections-a02'),
      rule('Same time? Look right', [
        'The driver on the left yields. Confirm that the other driver is actually moving.',
        'If two vehicles reach an uncontrolled intersection together, the vehicle on the right goes first.',
        'The same left-yields-to-right pattern applies at an all-way stop after both vehicles have stopped.',
      ]),
      recall('Recall · Same-time arrival', 'Arriving together? The [[left]] driver yields to the driver on the [[right]].'),
      rule('A T-intersection has a continuing road', [
        'Traffic on the ending road yields. People in the intersection still come first.',
        'At an uncontrolled T-intersection, traffic on the continuing road goes first.',
        'This is not permission for through traffic to ignore a collision risk. Both drivers still watch, slow, and protect people in the intersection.',
      ]),
      visual('Blocked views demand less speed', [
        'Cover the brake. Move only far enough to see.',
        'The goal is to prevent two road users from choosing the same space.',
        'Slow enough to see cross traffic, bicycles, and pedestrians.',
        'Yield when the rule requires it or when proceeding would cause a crash. Do not insist on priority when another person is already moving into the conflict.',
      ]),
      image('uncontrolled-intersections-a03'),
      related('Eye contact is not a legal signal', [
        'A driver may look at you and still move. Trust space and speed, not a glance.',
        'Right-of-way rules make crossing paths predictable.',
        'They do not create a shield around the vehicle that technically goes first.',
        'Use the rule to organize movement, then confirm that the other road user is actually yielding before you enter the conflict.',
      ]),
      rule('Narrow roads and steep grades', [
        'When two vehicles meet where neither can pass, the one with the easier retreat backs up to the nearest safe space.',
        'On a steep grade that is usually the vehicle facing downhill, because it can reverse uphill under control.',
        'Do not squeeze past. Drive at a speed that lets you stop within the road you can see.',
      ]),
      recall('Recall · Narrow roads', 'On a narrow steep road, the vehicle facing [[downhill]] usually backs up to make room.'),
      rule('Right-of-way is never forced', [
        'Give up your turn when a crash is developing. Safety beats being technically first.',
        'Right-of-way is something the other road user yields; it is not something you force.',
        'If another driver fails to follow the sequence, give up the turn rather than turn a correct exam answer into a crash.',
        'A procession led by an officer, an emergency vehicle, or a funeral escort also goes first. Never cut into it.',
      ]),
      recall('Recall · Never forced', 'Right-of-way is [[yielded]] by others, never [[forced]] by you.'),
    ],
    test: [
      q('Who should yield?', ['Both should enter together', 'You should yield to the car on your right', 'The car on your right must yield'], 1, 'If two vehicles reach an uncontrolled intersection together, the vehicle on the right goes first.', { image: 'uncontrolled-intersections-q01-a' }),
      q('Another vehicle is already in the uncontrolled intersection. What should you do?', ['Enter because you are on the wider road', 'Pass behind it without slowing', 'Yield until the path is clear'], 2, 'The approaching driver yields to a vehicle already in the intersection.', { image: 'uncontrolled-intersections-q02-a' }),
      q('At an all-way stop, one vehicle clearly stopped before you. Who normally proceeds first?', ['The vehicle on the wider street', 'Whichever driver signals with headlights', 'The vehicle that stopped first'], 2, 'Clear arrival order normally sets the sequence after each required stop.', { image: 'uncontrolled-intersections-q03-a' }),
      q('Cars arrive at the same time; the other car is directly to your left. Who yields?', ['The other car', 'You', 'Neither'], 0, 'The driver on the left yields to the vehicle on the immediate right.', { image: 'uncontrolled-intersections-q04-a' }),
      q('Your road ends at a T intersection with no signs. What is your duty?', ['Yield to traffic on the continuing road', 'Assume the through road will stop', 'Enter first if turning right'], 0, 'Traffic on the terminating road yields to the continuing road.', { image: 'uncontrolled-intersections-q05-a' }),
      q('The rule says you go first, but the other driver is already rolling into the intersection. What should you do?', ['Enter anyway; the rule is on your side', 'Give up the turn and let the vehicle clear', 'Sound the horn and accelerate'], 1, 'Right-of-way is yielded, never forced. Give up the turn rather than cause a crash.'),
    ],
  }),

  lesson('crosswalks-and-roundabouts', {
    title: 'People in Your Path',
    objective: 'Pedestrians can be hard to see and have no protection from your car.',
    keyPoints: ['Scan before the crosswalk.', 'Protect blind pedestrians.', 'Yield before a roundabout.'],
    challenge: challenge(
      'A car is stopped at a crosswalk in the next lane.',
      'What should you do?',
      ['Pass it', 'Slow and prepare to stop', 'Honk and continue'],
      1,
      'The stopped car may be hiding a pedestrian.',
      { image: 'crosswalks-and-roundabouts-a01' },
    ),
    cards: [
      rule('A crosswalk may be unmarked', [
        'Intersection corners can form a crosswalk without painted lines. Scan both sides.',
        'Yield to a pedestrian crossing within a marked or unmarked crosswalk.',
        'A pedestrian crossing elsewhere must yield to vehicles close enough to be an immediate hazard, but drivers still owe due care and must avoid injury when possible.',
      ]),
      recall('Recall · Unmarked crosswalks', 'A crosswalk can be [[unmarked]] — pedestrian right-of-way still applies.'),
      rule('Slow before the person appears', [
        'Parked cars and large vehicles can block your view. Expect movement from the side.',
        'A pedestrian may be difficult to see until you are very close.',
        'Scan sidewalks, corners, parked vehicles, and median islands.',
        'Wait until the pedestrian is safely out of your path before proceeding.',
      ]),
      image('crosswalks-and-roundabouts-a02'),
      rule('Do not pass a stopped crosswalk vehicle', [
        'It may be protecting someone you cannot see. Stop and check.',
        'Do not overtake and pass a vehicle stopped at a crosswalk to let a pedestrian cross.',
        'The stopped vehicle blocks your view and may be the only clue that someone is in front of it.',
        'Cover the brake and wait until the entire crossing is visible and safe.',
      ]),
      rule('Blind pedestrians need predictable traffic', [
        'A white cane or a guide dog is an important clue. Stop and stay quiet.',
        'The person may rely on traffic sounds and predictable vehicle movement.',
        'Stop and yield; do not use the horn to invite the person across.',
        'Do not block the crosswalk or stop so close that engine noise is misleading. Remain still until the person is safely clear of your path.',
      ]),
      visual('Do not wave someone into danger', [
        'Another lane may still be moving. Yield without giving a risky signal.',
        'Yield to a pedestrian in a marked or unmarked crosswalk and exercise due care.',
        'A pedestrian must not step out so close that a driver cannot stop safely, but that does not remove your duty to watch, slow, and avoid a collision.',
      ]),
      image('crosswalks-and-roundabouts-a03'),
      rule('Roundabout traffic already inside goes first', [
        'Slow before the entry. Choose a safe gap and enter in the correct direction.',
        'Enter heading to the right of the central island. Inside, everyone moves counterclockwise; do not stop or pass.',
        'Missed your exit? Circle around once more.',
        'Read the signs and lane arrows, choose the lane before entry, and signal the exit when required.',
      ]),
      recall('Recall · Crosswalks and circles', 'Never pass a vehicle [[stopped]] at a crosswalk. Entering a roundabout, yield to traffic [[already inside]].'),
      trap('Choose the roundabout lane early', [
        'Signs and arrows show the lane for your exit. Avoid changing lanes inside.',
        '“The pedestrian should have yielded” is not a safe answer if the driver can still prevent harm.',
        'The test may ask who had a duty and what the driver should do next. Those are related but not identical questions.',
      ]),
      recall('Recall · Roundabout direction', 'Enter to the [[right]] of the central island and move [[counterclockwise]].'),
      remember('Exit with a final check', [
        'Signal when useful. Watch the crosswalk beyond the roundabout.',
        'Pedestrian safety questions are about what you cannot see as much as what you can.',
        'Crosswalk rules, blind-pedestrian protections, and roundabout entry controls all reward the same habit: approach slowly enough to discover the conflict before entering it.',
      ]),
    ],
    test: [
      q('How should you respond to the vehicle stopped at the crosswalk?', ['Pass because your lane is clear', 'Sound the horn and continue', 'Slow and stop; do not pass the stopped vehicle'], 2, 'A vehicle stopped at a crosswalk may be hiding a pedestrian; passing it is prohibited.', { image: 'crosswalks-and-roundabouts-q01-a' }),
      q('A pedestrian is crossing at an unmarked crosswalk. What is the driver’s duty?', ['Treat the crossing as nonexistent', 'Accelerate before the pedestrian reaches the lane', 'Yield and use due care'], 2, 'The crosswalk duty covers marked and unmarked crosswalks.', { image: 'crosswalks-and-roundabouts-q02-a' }),
      q('Why must you not pass a vehicle stopped at a crosswalk?', ['It may conceal a crossing pedestrian', 'Stopped vehicles always have mechanical trouble', 'Passing is allowed only at night'], 0, 'The stopped vehicle may hide a person in the crossing.', { image: 'crosswalks-and-roundabouts-q03-a' }),
      q('You see a person with a white cane entering the roadway. What should you do?', ['Pass closely before they continue', 'Yield and take precautions to avoid injury', 'Assume the person sees your car'], 1, 'The driver must yield to a blind pedestrian using a white cane or a guide dog.', { image: 'crosswalks-and-roundabouts-q04-a' }),
      q('Who should yield at a roundabout entrance?', ['Entering traffic', 'Traffic already circulating', 'Only pedestrians'], 0, 'YIELD control is placed on roundabout approaches, so entering traffic gives way to circulating traffic.', { image: 'crosswalks-and-roundabouts-q05-a' }),
      q('A blind pedestrian with a white cane is waiting to cross. What should you do?', ['Honk to signal that you are stopping', 'Stop, remain predictable, and yield', 'Drive through quickly before the pedestrian steps out'], 1, 'Yield and stay predictable. Do not use the horn as an invitation because it can confuse a pedestrian who relies on sound.'),
    ],
  }),

  lesson('complex-intersections', {
    title: 'Read the Whole Intersection',
    objective: 'Busy intersections stack signals, arrows, and lane rules. Read them in one order.',
    keyPoints: ['Find the signal for your lane.', 'Know which turns are protected.', 'Finish in the correct lane.'],
    challenge: challenge(
      'You wait to turn left. Your signal shows a flashing yellow arrow, and oncoming traffic keeps coming.',
      'What should you do?',
      ['Turn now — the arrow allows it', 'Yield to oncoming traffic, then turn when clear', 'Stop and wait for a green arrow'],
      1,
      'A flashing yellow arrow allows the turn only after you yield. It is not a protected turn.',
      { image: 'complex-intersections-ca-traffic-signals-a01' },
    ),
    cards: [
      rule('Every lane has its own signal', [
        'A big intersection can show several signal heads at once. Find the one over your lane before anything else.',
        'A circular light speaks to everyone moving in that direction. An arrow speaks only to the turn it points at.',
        'Signs on the corner can add or remove options.',
      ]),
      rule('A green arrow is a promise', [
        'A green arrow means a protected turn. Oncoming traffic is held by a red light.',
        'A green circle makes a different offer. You may turn, but you must yield to oncoming traffic and pedestrians first.',
        'Same direction, very different duties.',
      ]),
      image('complex-intersections-ca-turns-and-signals-q03-a'),
      rule('Yellow arrows end the protection', [
        'A steady yellow arrow means your protected time is ending.',
        'Already in the intersection? Complete the turn with care.',
        'A flashing yellow arrow never protects you.',
        'Turn only after yielding to oncoming traffic, and watch for people crossing.',
      ]),
      recall('Recall · Flashing yellow arrow', 'A flashing yellow arrow means turn only after [[yielding]] — the turn is not [[protected]].'),
      rule('A red arrow closes the turn', [
        'A red arrow means stop and wait for a green light or a green arrow.',
        'Do not confuse it with a plain red light, where a right turn is usually allowed after a full stop unless a sign prohibits it.',
        'Your state decides whether any turn is possible on a red arrow; when in doubt, wait.',
      ]),
      recall('Recall · Red arrow', 'A red arrow means [[stop]] and wait for a [[green]] indication. Right on red applies to a plain red light.'),
      rule('Finish in the matching lane', [
        'Turns have a home lane on both ends.',
        'Right turns start near the right edge and end there. Do not swing wide.',
        'A left turn onto a two-way street ends in the lane closest to the middle.',
        'Turning onto a one-way street? Read the arrows; often any lawful lane is open to you.',
      ]),
      image('complex-intersections-ca-turns-and-signals-a02'),
      rule('An island lane keeps moving', [
        'Some right turns get a dedicated lane behind an island. It does not merge with through traffic.',
        'You may keep moving even when the through lanes face a red light.',
        'Obey the lane’s own light or sign, and always yield to pedestrians in the crosswalk.',
      ]),
      recall('Recall · Finishing lane', 'Right turns begin and end near the [[right edge]]; a left turn onto a two-way street ends closest to the [[middle]].'),
      remember('One order for every intersection', [
        'Read the signs first. They set the rules of the place.',
        'Then find your lane’s signal and its arrows.',
        'Then people: crosswalks, cyclists, and anyone still clearing the road.',
        'Then pick the gap that lets you finish in the right lane.',
        'The pieces live in earlier lessons — lights, STOP and YIELD, who goes first, people in your path. This is where they meet.',
      ]),
    ],
    test: [
      q('Your left-turn signal changes from a green arrow to a steady yellow arrow while you are already inside the intersection.', ['Stop where you are', 'Cautiously complete the turn', 'Reverse behind the stop line'], 1, 'A yellow arrow means the protected time is ending. A driver already in the intersection completes the turn carefully.'),
      q('You face a flashing yellow arrow for your left turn. A pedestrian is crossing the street you are turning into.', ['Turn behind the pedestrian right away', 'Yield to the pedestrian and oncoming traffic, then turn', 'Wait — this arrow never allows a turn'], 1, 'A flashing yellow arrow allows the turn only after yielding to oncoming traffic and anyone crossing.'),
      q('Your lane faces a steady red arrow. What does it require?', ['Stop and wait for a green light or green arrow', 'Turn immediately without stopping', 'Speed up to clear the intersection'], 0, 'A red arrow means stop and wait; the turn resumes only on a green indication.'),
      q('You turn left from a two-way street onto another two-way street.', ['End in the left lane closest to the middle', 'End in any lane that looks open', 'End near the right curb'], 0, 'A left turn onto a two-way street finishes in the lane nearest the center line.'),
      q('A dedicated right-turn lane curves behind an island. The through lanes face a red light.', ['Stop and wait for green with the through traffic', 'Keep moving under the lane’s own light or sign, yielding to pedestrians', 'Merge left into the through lanes'], 1, 'A dedicated right-turn lane does not merge and keeps moving under its own controls, with pedestrians protected.'),
      q('A green circle — not an arrow — faces you as you wait to turn left.', ['The turn is protected', 'Turn only after yielding to oncoming traffic and pedestrians', 'Left turns are not allowed on a green circle'], 1, 'A green circular light permits the turn but does not protect it. Yield first, then turn.'),
    ],
  }),

  lesson('u-turns-starting-backing', {
    title: 'Driveways, Backing, and U-Turns',
    objective: 'Slow maneuvers still create serious conflicts.',
    keyPoints: ['Look around before moving.', 'Back at walking speed.', 'Check every U-turn condition.'],
    challenge: challenge(
      'You miss your freeway exit.',
      'What is the safe choice?',
      ['Back along the shoulder', 'Continue to the next exit', 'Use the median'],
      1,
      'Keep going. Never reverse to recover a missed freeway exit.',
      { image: 'u-turns-starting-backing-a01' },
    ),
    cards: [
      why('Check before the car moves', [
        'Walk around when a child or an object may be hidden. Use mirrors and a shoulder check.',
        'Mirrors and cameras help, but they do not show every person or object.',
        'Look over the appropriate shoulder and back at walking speed.',
        'Stop whenever your view becomes uncertain.',
      ]),
      rule('Back slowly', [
        'Look in the direction you are moving. Stop when the view becomes uncertain.',
        'Do not start from a stopped or parked position, and do not back up on a road, until the movement can be made with reasonable safety.',
        'Check behind, beside, and for small road users hidden below the windows.',
        'Move slowly enough to stop immediately if the scene changes.',
      ]),
      image('u-turns-starting-backing-a02'),
      visual('Cameras do not show everything', [
        'A lens can miss low, close, or side hazards. Use it as one tool, not the only tool.',
        'Turn your head. Check the mirrors, the camera, and then the mirrors again as you roll.',
        'A pedestrian behind the bumper is often visible only in one of them.',
      ]),
      rule('Driveways cross sidewalks', [
        'Yield to people before entering the road. Then find a safe traffic gap.',
        'Cross the sidewalk only after checking for pedestrians, wheelchairs, and bicycles.',
        'Estimate conservatively; the purpose is a clear, usable gap, not the smallest one you can fit.',
      ]),
      rule('A U-turn needs legal space', [
        'Check signs, lane position, traffic, and visibility. Possible does not always mean legal.',
        'A U-turn can look physically possible and still be illegal because of the location, visibility, or approaching traffic.',
        'Start from the far-left lawful lane and yield to everything approaching.',
        'Backing has the same underlying rule: begin only when the movement can be made with reasonable safety.',
      ]),
      image('u-turns-starting-backing-a03'),
      rule('You must see far enough', [
        'Never turn around where a hill or a curve hides you from approaching drivers.',
        'In {{state}} that means an unobstructed view for {{uturn.visibilityFeet}} feet in both directions.',
        'Good visibility does not cancel a location prohibition such as a posted sign.',
        'Other location rules can still prohibit the turn, so read the exact place in the question.',
      ]),
      recall('Recall · U-turn visibility', 'A U-turn needs an unobstructed view for [[{{uturn.visibilityFeet}} feet]] in both directions.'),
      trap('Do not apply one U-turn rule everywhere', [
        'Read the exact location in the question.',
        'The exam may change the location, the signal control, the visibility, the business or residential context, or a nearby fire station.',
        'Each of those can make the same U-turn legal or illegal.',
      ]),
      remember('Missed your move?', [
        'Continue to a legal place. A wrong route is safer than a sudden reversal.',
        'A missed turn or driveway is not an emergency.',
        'Do not back on a freeway or across traffic to recover a missed exit.',
        'Make a U-turn only when it is legal and you can see far enough in both directions.',
      ]),
      recall('Recall · Missed exit', 'Never back up on a [[freeway]] to recover a missed exit — continue to the next [[exit]].'),
    ],
    test: [
      q('Is the U-turn allowed?', ['Yes, residential U-turns are always allowed', 'Yes, if you do not signal', 'No, the approaching vehicle is too close'], 2, 'A U-turn must yield to approaching traffic; a vehicle this close makes the turn unsafe and unlawful.', { image: 'u-turns-starting-backing-q01-a' }),
      q('Where is a U-turn normally considered in a busy business district?', ['At an intersection or a provided opening in a divided highway', 'Midblock anywhere', 'Across a sidewalk'], 0, 'Business-district U-turns are limited to intersections or provided openings, where visibility and control are better.', { image: 'u-turns-starting-backing-q02-a' }),
      q('What can make a physically possible U-turn illegal?', ['Only the time of day', 'The location, the visibility, or approaching traffic', 'Nothing, if you signal'], 1, 'Location rules, sight distance, and approaching traffic each decide whether the turn is lawful.', { image: 'u-turns-starting-backing-q03-a' }),
      q('You have a clear view in both directions, but a sign prohibits U-turns here. May you turn?', ['Only with hazard lights', 'No', 'Yes, visibility overrides the sign'], 1, 'A posted prohibition remains even when visibility is adequate.', { image: 'u-turns-starting-backing-q04-a' }),
      q('Before backing from a curb, what is required?', ['Confirm the movement can be made with reasonable safety', 'Rely only on the rear camera', 'Back quickly before traffic arrives'], 0, 'The driver must verify that starting or backing can be done with reasonable safety.', { image: 'u-turns-starting-backing-q05-a' }),
      q('You miss your freeway exit. What is the safest response?', ['Back along the shoulder', 'Continue to the next exit', 'Make a U-turn through the median'], 1, 'Continue to the next exit. Never back up or make an unsafe reversal to recover a missed freeway exit.'),
    ],
  }),

  lesson('parking-and-curbs', {
    title: 'Park Without Getting a Ticket',
    objective: 'Good parking protects visibility, access, and moving traffic.',
    keyPoints: ['Read signs and curbs.', 'Secure the car on hills.', 'Leave the curb safely.'],
    challenge: challenge(
      'You park downhill beside a curb.',
      'Where should the front wheels point?',
      ['Toward the curb', 'Away from the curb', 'Straight ahead'],
      0,
      'Turn toward the curb so a rolling car moves away from traffic.',
      { image: 'parking-and-curbs-a01' },
    ),
    cards: [
      rule('Check the place before the technique', [
        'A perfect parking move is still illegal in a prohibited spot. Read the signs and curb markings first.',
        'Double parking — waiting in the road beside a parked car — is on the never list, even briefly.',
        'Stay at least {{parking.hydrantFeet}} feet from a fire hydrant unless a legal exception applies.',
        'Posted local time limits still control how long you may stay.',
      ]),
      rule('Parallel parking stays slow', [
        'Signal and stop beside the vehicle ahead of the space.',
        'Check mirrors, blind spots, pedestrians, bicycles, and traffic.',
        'Back slowly into the space, straighten, and center without touching other vehicles.',
        'Accuracy comes from low speed and repeated checks, not one fast steering move.',
      ]),
      rule('Stay close to the curb', [
        'Park in the lawful direction, on the correct side, and within {{parking.curbInches}} inches of the curb.',
        'One-way roads can change the allowed side.',
        'Before leaving, stop the engine and set the parking brake.',
        'On a hill, turn the front wheels so a rolling car moves away from danger.',
      ]),
      recall('Recall · Parking distances', 'Park within [[{{parking.curbInches}} inches]] of the curb and at least [[{{parking.hydrantFeet}} feet]] from a fire hydrant.'),
      rule('Never park here', [
        'Set the parking brake and use Park or the correct gear before leaving.',
        'Stopping, standing, or parking is prohibited where the vehicle blocks traffic or access.',
        'Common conflicts include sidewalks, crosswalks, driveways, intersections, bus stops, and the lane of a freeway.',
        'A quick errand does not turn a prohibited place into a legal one.',
      ]),
      recall('Recall · Hill parking', 'Turn the wheels so a rolling car goes toward the [[curb]] or edge, and set the [[parking brake]].'),
      rule('Hill parking controls a possible roll', [
        'With a curb, turn the wheels so the curb can stop the car. Without a curb, turn toward the road edge.',
        'Downhill: turn toward the curb. Uphill with a curb: turn away from the curb and let the tire rest against it.',
        'Wheel direction is only one part. Set the parking brake and place the transmission in Park or the proper gear.',
        'Before pulling out, signal and check traffic and blind spots.',
      ]),
      recall('Recall · Double parking', 'Stopping in the road beside a parked car is [[double parking]] — [[illegal]], even briefly.'),
      image('parking-and-curbs-a03'),
      rule('Hydrants need clear space', [
        'Keep at least {{parking.hydrantFeet}} feet of space from a fire hydrant. A legal exception must be clear.',
        '“I will be quick” does not erase a prohibited stopping place.',
        'The law may regulate stopping or standing even when the driver stays in the car.',
      ]),
      rule('Accessible spaces are protected', [
        'Use them only with a valid placard or plate, and keep the access aisles clear.',
        'Parking rules protect sight lines, access, traffic flow, and people who must cross or open doors.',
        'Solve them by checking the place, the measured clearance, the curb control, the vehicle position, and the safe exit.',
      ]),
      rule('Leaving is another maneuver', [
        'Signal, then check mirrors and blind spots.',
        'Enter only when the gap is safe.',
        'Open a door into moving traffic only when reasonably safe, and leave it open no longer than necessary.',
        'Check for bicycles and motorcycles before exiting.',
        'On a freeway, stopping is exceptional; a real emergency should be handled as far from moving lanes as possible.',
      ]),
    ],
    test: [
      q('May you park there?', ['Yes, if you leave the engine running', 'No, you must remain at least {{parking.hydrantFeet}} feet away unless an exception applies', 'Yes, because the vehicle fits'], 1, 'Parking within {{parking.hydrantFeet}} feet of a fire hydrant is prohibited unless a legal exception applies.', { image: 'parking-and-curbs-a01' }),
      q('Is a marked crosswalk a lawful parking space when no pedestrian is present?', ['No', 'Yes', 'Only for five minutes'], 0, 'A crosswalk is a prohibited parking location.', { image: 'parking-and-curbs-a01' }),
      q('How close to the curb must a parallel-parked vehicle be in {{state}}?', ['Touching the curb in every case', 'Within {{parking.curbInches}} inches', 'Within three feet'], 1, 'The general maximum is {{parking.curbInches}} inches from the appropriate curb.', { image: 'parking-and-curbs-a01' }),
      q('Who may use an accessible parking space?', ['An authorized disabled person or qualifying vehicle', 'Any driver for a quick stop', 'Delivery vehicles only'], 0, 'Accessible spaces are reserved for authorized disabled parking.', { image: 'parking-and-curbs-a03' }),
      q('What must you check before opening a street-side door?', ['Only the interior light', 'Whether the engine is warm', 'Approaching traffic, including bicycles'], 2, 'The door may enter a moving path and must be opened only when reasonably safe.', { image: 'parking-and-curbs-a03' }),
      q('After parking on a hill, what should you do in addition to turning the wheels correctly?', ['Leave the transmission in Neutral', 'Set the parking brake and secure the transmission', 'Keep the engine running'], 1, 'Secure the vehicle with the parking brake and the correct transmission position before leaving it.'),
    ],
  }),
];
