// Module 4 · Lanes, Passing, and Freeways — universal skeleton.
import {
  lesson,
  why,
  rule,
  related,
  remember,
  trap,
  visual,
  image,
  recall,
  challenge,
  q,
} from '../helpers.mjs';

export const LESSONS = [
  lesson('choosing-changing-lanes', {
    title: 'Choose the Right Lane',
    objective: 'Good lane choices prevent sudden moves later.',
    keyPoints: ['Plan your lane early.', 'Check every blind spot.', 'Change one lane at a time.'],
    challenge: challenge(
      'Your mirror looks clear before a lane change.',
      'What should you do next?',
      ['Move immediately', 'Check the blind spot', 'Brake in your lane'],
      1,
      'Mirrors leave blind spots. Look over your shoulder before moving.',
      { image: 'choosing-changing-lanes-a01' },
    ),
    cards: [
      why('Choose early', [
        'Use signs, arrows, and your route. Last-second lane changes create extra risk.',
        'On a two-lane road where passing is unsafe, a slow vehicle with a line of traffic behind it should use a turnout or another safe area to let the queue pass.',
        'Do not pull off where the surface or the sight distance makes the cure more dangerous than the delay.',
      ]),
      rule('Use the full check', [
        'A turn signal shows what you plan to do. It does not give you the right to move.',
        'Check mirrors for traffic approaching from behind. Look over your shoulder for the blind spot.',
        'Move only when the gap is large enough. Do not force another driver to brake.',
        'Check the space in this order:',
      ], { bullets: ['Mirror.', 'Signal.', 'Blind spot.', 'Gap.', 'Then move.'] }),
      recall('Recall · Lane change', 'Before moving sideways: signal, mirrors, then a head check of the [[blind spot]].'),
      image('choosing-changing-lanes-a02'),
      visual('One lane at a time', [
        'Finish one lane change before starting another. Keep the signal useful and clear.',
        'Drive on the right half of the road unless an exception applies, such as legal passing, an obstruction, or a one-way road.',
        'When moving slower than traffic, stay in the right lane or near the right edge.',
        'Move left when passing or preparing for a left turn.',
      ]),
      recall('Recall · One at a time', 'Change [[one]] lane at a time — settle, recheck, then move again.'),
      related('Do not camp beside another car', [
        'That car may need your lane. Move ahead or drop back when safe.',
        'Keep the vehicle as nearly as practical within a single lane. Do not drift across a line while searching for a gap.',
        'Before moving, check traffic ahead, beside, and behind; signal when others may be affected; and wait until the destination lane has enough usable space.',
      ]),
      rule('Traffic breaks need patience', [
        'An officer may weave across lanes to slow traffic and create space ahead for a hazard or an operation.',
        'Do not try to pass the patrol vehicle or race the controlled pattern.',
        'Reduce speed smoothly and follow its directions.',
        'Expect stopped traffic or an incident beyond the point you can see.',
      ]),
      image('choosing-changing-lanes-a03'),
      rule('A lane can end quickly', [
        'Plan a merge when the warning appears. Do not wait for the pavement to disappear.',
        'A mirror shows only the angle reflected into it.',
        'Motorcycles, bicycles, and cars can travel in the uncovered zone slightly behind either side.',
        'Turn your head enough to check through the side window without turning the steering wheel or your whole body.',
      ]),
      remember('Missed the lane?', [
        'Continue safely and reroute. Do not cut across traffic or painted barriers.',
        'A signal is a request for space, not proof that space exists.',
        'An answer that says “signal and move” but omits observation can still be wrong.',
        'Choose a lane that fits your speed and your next move. Stay centered, signal early, and keep a steady speed and a smooth path.',
      ]),
    ],
    test: [
      q('What must happen before you move?', ['Rely on the rearview mirror alone', 'Signal, check mirrors, and directly check the blind spot', 'Move first and signal afterward'], 1, 'A lane change must be reasonably safe, and mirrors do not reveal every blind spot.', { image: 'choosing-changing-lanes-q01-a' }),
      q('You are moving slower than normal traffic on a multilane road. Where should you generally drive?', ['In the far-left lane', 'Across two lanes', 'In the right-hand lane'], 2, 'Slower traffic generally keeps right unless passing or preparing for a left turn.', { image: 'choosing-changing-lanes-q02-a' }),
      q('Traffic is lined up behind you on a two-lane road where passing is unsafe. What should you do when a safe turnout is available?', ['Increase speed beyond what is safe', 'Stop in the travel lane', 'Use it to let traffic pass'], 2, 'A slow vehicle releases the queue at a turnout or another safe place instead of holding it.', { image: 'choosing-changing-lanes-q03-a' }),
      q('May you begin drifting into the next lane while checking whether it is clear?', ['Yes, if traffic is slow', 'Only on a curve', 'No'], 2, 'Remain within the lane until the lateral movement can be made with reasonable safety.', { image: 'choosing-changing-lanes-q04-a' }),
      q('What does the shoulder check add to a mirror check?', ['Permission to skip signaling', 'A direct view into the blind spot', 'A speed-limit reading'], 1, 'The direct shoulder check covers road users hidden from the mirrors.', { image: 'choosing-changing-lanes-q05-a' }),
      q('You signal a lane change, but a vehicle is still in your blind spot. What should you do?', ['Move because the signal gives you priority', 'Wait until the blind spot and target gap are clear', 'Speed up and force the other driver behind you'], 1, 'A signal communicates your plan; it never makes an unsafe gap available.'),
    ],
  }),

  lesson('passing-rules', {
    title: 'Pass—or Wait?',
    objective: 'Passing needs legal permission, enough sight distance, and a safe return.',
    keyPoints: ['Check the markings.', 'See the whole passing path.', 'Return without cutting in.'],
    challenge: challenge(
      'A hill hides the road ahead on a two-lane road.',
      'Should you pass?',
      ['Yes, if you accelerate', 'No, wait for a clear view', 'Yes, if the other car is slow'],
      1,
      'Never use an opposing lane when the view ahead is blocked.',
      { image: 'passing-rules-a01' },
    ),
    cards: [
      rule('Passing begins with permission', [
        'Check signs and lane markings. A safe-looking gap does not cancel a restriction.',
        'Curves, grades, intersections, and railroad approaches create no-passing conditions because you cannot see the whole path.',
        'A quick maneuver does not remove the hidden conflict.',
        'Read signs and markings, but also identify the roadway feature.',
      ]),
      rule('See the complete path', [
        'You need room to move out, pass, and return. Do not guess beyond a hill or a curve.',
        'Do not move into oncoming traffic until you can see far enough ahead.',
        'Make sure the lane stays clear for the entire pass.',
        'If you cannot see the full decision, you do not have a passing opportunity.',
      ]),
      image('passing-rules-a02'),
      visual('Check behind before moving out', [
        'Another driver may already be passing. Use mirrors and a blind-spot check.',
        'Overtake safely to the left unless a specific right-side rule applies.',
        'Do not return to the original lane until you are safely clear of the vehicle.',
        'Check mirrors and blind spots before both the outward move and the return.',
      ]),
      rule('Pass with a clear speed difference', [
        'Do not stay beside the other vehicle. Finish without exceeding the legal speed.',
        'A pass must be both legal and safe for the conditions.',
        'A legal location can still be unsafe because of sight distance, oncoming traffic, speed difference, a bicycle, or the space needed to return.',
      ]),
      visual('Return with space', [
        'See the passed vehicle clearly in your mirror. Do not cut closely in front.',
        'Do not begin with only enough space to pull out. See the full distance needed to pass and return.',
        'Check for driveways, intersections, hills, curves, and changing markings.',
        'Cancel the pass early if any part of the plan becomes uncertain.',
      ]),
      image('passing-rules-a03'),
      rule('Never pass near certain conflicts', [
        'Crossings, intersections, bridges, and blocked views prohibit passing. Read the exact scenario.',
        'Right-side passing is allowed only in listed roadway situations and only when it can be completed safely.',
        'Never leave the paved roadway to get around another vehicle. An unpaved shoulder is not a passing lane.',
      ]),
      recall('Recall · Clear-view pass', 'Do not move into oncoming traffic until you can see far enough [[ahead]] to complete the whole pass.'),
      rule('When someone passes you', [
        'Keep a steady path and do not speed up.',
        'When being passed, hold a steady course; a driver who accelerates traps the other car in the opposing lane.',
        'Move slightly right or slow a little when safe, instead of competing with the passing driver.',
      ]),
      recall('Recall · No-pass spots', 'Skip the pass near an intersection, a railroad [[crossing]], or a hidden [[curve]].'),
      remember('Waiting is a valid decision', [
        'A few seconds can remove the risk. Pass only when every part of the path works.',
        '“The line is broken” answers only one part of the question.',
        'Look for a hidden curve, hill, intersection, railroad crossing, oncoming vehicle, or an insufficient return gap.',
      ]),
    ],
    test: [
      q('Should you pass now?', ['Yes, if you exceed the speed limit briefly', 'No, wait for a clearly visible safe path', 'Yes, the broken line guarantees safety'], 1, 'A marking may permit crossing, but the pass still requires a clear view and enough distance.', { image: 'passing-rules-a01' }),
      q('When may you return to the original lane after passing?', ['When safely clear of the overtaken vehicle', 'As soon as your front bumper is ahead', 'Whenever the other driver slows'], 0, 'The law requires returning right only when safely clear.', { image: 'passing-rules-a01' }),
      q('The centerline permits passing, but a hill blocks your view. What controls?', ['Wait for clear sight distance', 'The broken line alone', 'The speed of the car behind'], 0, 'A clear view and an empty opposing path are required in addition to permissive markings.', { image: 'passing-rules-a02' }),
      q('Why is passing near a crest dangerous?', ['Oncoming traffic may be hidden', 'The road is always narrower', 'Turn signals stop working'], 0, 'A crest can hide an approaching vehicle until there is no safe recovery distance.', { image: 'passing-rules-a03' }),
      q('May you use an unpaved shoulder to pass a car waiting to turn left?', ['Yes, whenever the car is stopped', 'Only if you honk', 'No'], 2, 'A pass may not be made by leaving the paved roadway.', { image: 'passing-rules-a03' }),
      q('Another driver begins passing you on a two-lane road. What should you do?', ['Increase speed so the driver returns behind you', 'Keep a steady course and do not increase speed', 'Move toward the centerline'], 1, 'Be predictable and do not increase speed while another vehicle is passing.'),
    ],
  }),

  lesson('freeway-merging', {
    title: 'Enter and Leave the Freeway',
    objective: 'Freeway driving works best when speed and lane choices are planned early.',
    keyPoints: ['Match traffic before merging.', 'Protect following space.', 'Never reverse for an exit.'],
    challenge: challenge(
      'You are entering from an acceleration lane.',
      'What is the main goal?',
      ['Stop at the lane end', 'Match traffic and find a gap', 'Enter at a very low speed'],
      1,
      'Use the ramp to build a safe speed and join a real gap.',
      { image: 'freeway-merging-a01' },
    ),
    cards: [
      why('Use the ramp to prepare', [
        'Build speed while scanning traffic. Do not wait until the merge point to look.',
        'Begin scanning the freeway while you still have ramp length.',
        'Identify the speed and spacing of several vehicles, not just one.',
        'A gap is useful only if you can reach it without an abrupt acceleration, brake, or sideways cut.',
      ]),
      rule('Freeway traffic has priority', [
        'Find a gap and adjust smoothly. Do not force another driver to brake.',
        'Use the acceleration lane to approach the freeway’s flow while staying within the law and the conditions.',
        'A large speed difference makes the merge harder for everyone.',
        'Do not assume freeway traffic must yield; enter only when the lane movement is reasonably safe.',
      ]),
      recall('Recall · Merging', 'Freeway traffic has [[priority]]. Use the whole [[acceleration lane]] to match its speed.'),
      image('freeway-merging-a02'),
      visual('Use the whole acceleration lane', [
        'More lane gives you more time. Stop only when traffic leaves no safe alternative.',
        'The acceleration lane gives you time to observe traffic and adjust speed.',
        'Find a gap before you reach the merge point. Match the flow without exceeding a safe and legal speed.',
      ]),
      rule('Once inside, rebuild space', [
        'Check your following gap. Avoid staying beside another vehicle.',
        'Stopping, standing, or parking on a freeway is prohibited except for an emergency or a designated location.',
        'If a real emergency forces a stop, move as far from traffic as possible and make the vehicle visible.',
      ]),
      visual('Plan the exit early', [
        'Read guide signs early and move toward the exit one safe lane at a time.',
        'Signal before the exit. Slow in the exit lane, not in the through lanes.',
        'If you miss the exit, continue to the next safe route; do not reverse, stop, or cross a painted gore.',
      ]),
      image('freeway-merging-a03'),
      related('Slow on the exit ramp', [
        'Leave freeway traffic at a stable speed. Reduce speed where the ramp allows it.',
        'Freeway questions reward early observation.',
        'Use the ramp and the auxiliary lane to understand the traffic stream, choose a gap, and make one smooth merge.',
        'Last-second moves create larger speed differences and smaller options.',
      ]),
      rule('Missed the exit?', [
        'Take the next one. Never stop, back up, or cross a gore area.',
        'Yielding on a ramp does not mean an automatic stop. Stopping can erase the speed and distance needed to merge.',
        'Choose the action that fits the traffic, the sign, and the available lane, not a universal ramp ritual.',
      ]),
      recall('Recall · Missed exit', 'Missed the exit? Continue to the [[next]] one — never stop or [[back up]] on the freeway.'),
      rule('Ramp signals control entry', [
        'A metering signal spaces vehicles entering a freeway.',
        'Stop at red at the marked line. Proceed on green for the number of vehicles the sign allows.',
        'After the signal, use the rest of the ramp to merge normally.',
      ]),
    ],
    test: [
      q('What is the best plan?', ['Adjust to the usable gap, signal, check the blind spot, and merge smoothly', 'Stop at the end of the ramp by default', 'Force the first vehicle to brake'], 0, 'A freeway merge is a planned lane movement into an available gap, not a claim to space.', { image: 'freeway-merging-a01' }),
      q('When should you begin selecting a freeway gap?', ['Only when another driver honks', 'Before reaching the merge point', 'After the lane ends'], 1, 'Early observation gives time to adjust smoothly to a usable gap.', { image: 'freeway-merging-a01' }),
      q('Who is responsible for finding a safe freeway entry gap?', ['The vehicle farthest behind', 'The entering driver', 'Only drivers already on the freeway'], 1, 'The entering driver must make the lane movement safely rather than force a gap.', { image: 'freeway-merging-a02' }),
      q('You miss your freeway exit. What should you do?', ['Stop in the through lane', 'Continue to the next safe route', 'Back up on the shoulder'], 1, 'Missing an exit does not justify a dangerous or unlawful recovery maneuver.', { image: 'freeway-merging-a03' }),
      q('May you stop on the freeway shoulder to check a map?', ['Not unless a legal or genuine safety exception applies', 'Yes, shoulders are general parking', 'Yes, for any phone use'], 0, 'Freeway stopping is prohibited except for emergencies and listed exceptions.', { image: 'freeway-merging-a03' }),
      q('When entering a freeway, what is the main purpose of the acceleration lane?', ['To stop until the freeway is empty', 'To find a gap and adjust to a safe merging speed', 'To pass freeway traffic on the right shoulder'], 1, 'Use the acceleration lane to observe traffic, choose a gap, and adjust speed before merging.'),
    ],
  }),

  lesson('special-lanes', {
    title: 'Lanes with Special Rules',
    objective: 'Some lanes are legal only for a certain move, vehicle, or time.',
    keyPoints: ['Read the posted condition.', 'Enter only where allowed.', 'Watch for people already in the lane.'],
    challenge: challenge(
      'You want to enter a carpool lane.',
      'What should you trust?',
      ['Yesterday’s rule', 'The current signs and markings', 'The car ahead'],
      1,
      'Occupancy, hours, access, and toll rules can change by location.',
      { image: 'special-lanes-a01' },
    ),
    cards: [
      why('A special lane has a specific job', [
        'Identify the lane before entering. Do not treat it as ordinary travel space.',
        'Special lanes are defined by the combination of markings, signs, users, and operating times.',
        'Treating them like ordinary travel lanes is a common exam error.',
      ]),
      rule('Center-turn lanes are for turns', [
        'A two-way left-turn lane sits in the middle of the road, marked by a solid yellow line outside and a broken yellow line inside.',
        'Use it only to prepare for a legal left turn or U-turn. Do not cruise or pass in it.',
        'In {{state}}, travel no more than {{centerLane.maxTravelFeet}} feet in the lane before the turn.',
        'Look for opposing drivers who may enter the same lane for their own turns.',
      ]),
      recall('Recall · Center turn lane', 'In a two-way left-turn lane, travel no more than [[{{centerLane.maxTravelFeet}} feet]].'),
      image('special-lanes-a02'),
      rule('Bicycle lanes carry real traffic', [
        'Check behind before crossing one. Enter for a turn only where allowed.',
        'A motor vehicle may enter a bicycle lane only to park where permitted, to enter or leave the road, or to prepare for a turn.',
        'For turn preparation, {{state}} allows entry within {{bikeLane.turnEntryFeet}} feet of the turn.',
        'Before crossing or entering, check the blind spot and yield to a bicyclist already using the lane.',
      ]),
      rule('Carpool and toll lanes use posted rules', [
        'Check occupancy, vehicle type, time, toll, and access point. Do not assume.',
        'Use a preferential lane only when your occupancy, vehicle class, access point, and time meet the signs and markings.',
        'Do not assume yesterday’s hours or another freeway’s occupancy rule applies here.',
        'Enter and leave only at permitted openings.',
      ]),
      recall('Recall · Posted lane rules', 'Carpool and toll lanes work only under their [[posted]] rules — occupancy, hours, and permits.'),
      image('special-lanes-a03'),
      rule('Transit lanes are not shortcuts', [
        'A limited entry may be allowed for a turn. Yield to buses or other authorized users.',
        'A special lane’s rules may change by location, time, direction, or vehicle.',
        'Follow solid and broken access markings. Do not assume a rule from one freeway applies to another.',
      ]),
      rule('Barriers are not passing areas', [
        'Painted medians and separated double lines form a barrier. Do not drive across it.',
        'A two-way left-turn lane has a different marking pattern and exists for permitted left turns or U-turns.',
        'Do not use either space as an ordinary passing lane.',
      ]),
      rule('Use turnouts when required and safe', [
        'A slow vehicle may need to let traffic pass. Reenter only with a safe gap.',
        'Transit lanes reserve space for specified vehicles; turnouts let a slower vehicle release a queue.',
        'Do not use a transit-only lane as a general travel lane.',
      ]),
    ],
    test: [
      q('How may you use this lane?', ['Drive in it until traffic clears for several blocks', 'Enter to prepare for the left turn, shortly before the turn', 'Use it as a passing lane'], 1, 'A two-way left-turn lane is for permitted turns or U-turns, entered shortly before the turn.', { image: 'special-lanes-a01' }),
      q('Can a painted barrier be used as a waiting lane for a left turn?', ['No', 'Yes, if you signal', 'Only during rush hour'], 0, 'A painted barrier is never a travel or waiting lane; the center left-turn lane is the marked exception.', { image: 'special-lanes-a01' }),
      q('Which use of a two-way left-turn lane is legal?', ['Passing slower traffic', 'Preparing for a left turn into a driveway', 'Cruising to the next intersection'], 1, 'The lane exists for preparing and making permitted left turns or U-turns.', { image: 'special-lanes-a02' }),
      q('What determines whether you may use a carpool lane now?', ['The color of your vehicle', 'Whether traffic is heavy', 'The posted occupancy, vehicle, access, and time rules'], 2, 'Carpool-lane eligibility is controlled by the official signs and markings for that lane.', { image: 'special-lanes-a03' }),
      q('When preparing for a turn, how far before the turn may a motor vehicle enter a bicycle lane in {{state}}?', ['Within {{bikeLane.turnEntryFeet}} feet of the turn', 'At any distance', 'Only after the crosswalk'], 0, 'The turn-preparation limit is within {{bikeLane.turnEntryFeet}} feet.', { image: 'special-lanes-a03' }),
      q('Before entering a carpool or toll lane, what should you rely on?', ['The rule from the last freeway you used', 'The signs and markings for that lane and time', 'Whether another car entered ahead of you'], 1, 'Special-lane conditions vary. Read the posted occupancy, vehicle, time, toll, and access rules.'),
    ],
  }),
];
