// Module 7 · The Driver and the Vehicle — universal skeleton.
import {
  lesson,
  why,
  rule,
  related,
  remember,
  trap,
  visual,
  image,
  recall,
  challenge,
  q,
} from '../helpers.mjs';

export const LESSONS = [
  lesson('distraction-and-fatigue', {
    title: 'Phones, Fatigue, and Road Rage',
    objective: 'Driving needs your eyes, hands, judgment, and emotional control.',
    keyPoints: ['Remove tasks before moving.', 'Stop when sleepiness appears.', 'Do not escalate conflict.'],
    challenge: challenge(
      'A message arrives while you are driving.',
      'What is the safe response?',
      ['Read it at the next light', 'Let it wait or pull over safely', 'Hold the phone below the window'],
      1,
      'The message can wait. Pull over safely if it truly cannot.',
      { image: 'distraction-and-fatigue-a01' },
    ),
    cards: [
      why('Distraction has several forms', [
        'Your eyes can leave the road. Your hands or mind can leave driving too.',
        'A driver can lose the road with eyes, hands, hearing, mind, or judgment.',
        'Device laws set minimum boundaries; safe attention often requires doing less than the maximum a device technically allows.',
      ]),
      rule('Set up before moving', [
        'Choose navigation, music, mirrors, and temperature first. Then put the phone away.',
        'A conversation can take attention even when your hands remain on the wheel.',
        'Let a passenger handle tasks or pull over safely.',
        'Do not read, type, eat, reach, or handle objects when it takes your eyes or mind from driving.',
      ]),
      image('distraction-and-fatigue-a02'),
      rule('The phone rule that applies everywhere', [
        'Reading or typing a message on a handheld phone while driving is illegal, and it is the most common cause of a distraction crash.',
        'Hands-free is the legal minimum in many places, not a guarantee of attention.',
        'A long task does not become acceptable because the phone is mounted or the light is red.',
      ]),
      rule('Young drivers have stricter rules', [
        'In {{state}}, a driver under {{phone.minorNoDeviceAge}} may not use a phone or a wireless device while driving, even hands-free, except in a genuine emergency.',
        'Do not borrow the adult rule for a question about a young driver.',
        'The law treats a real emergency differently from ordinary phone use.',
      ]),
      recall('Recall · Phones', 'Reading or typing on a [[handheld]] phone while driving is illegal — set everything up [[before]] you move.'),
      visual('Fatigue can copy impairment', [
        'Heavy eyes, missed signs, and drifting are warnings.',
        'Coffee may increase alertness briefly, but it does not replace sleep.',
        'A tired driver reacts late, misjudges gaps, and can fall asleep for seconds without noticing.',
        'Long night drives, heavy meals, and warm cabins make it worse; plan breaks before the trip starts.',
      ]),
      recall('Recall · Young drivers', 'A driver under [[{{phone.minorNoDeviceAge}}]] may not use a phone while driving — even [[hands-free]] — except in an emergency.'),
      image('distraction-and-fatigue-a03'),
      rule('Stop before you nod off', [
        'Leave the road at a safe place. Rest or change drivers.',
        'Stop the trip when fatigue prevents timely decisions.',
        'A short nap in a safe place beats another hour of fighting your eyelids.',
        'Reckless driving is more than a small mistake; it involves a conscious disregard for safety.',
      ]),
      trap('Road rage is a choice you can exit', [
        'Do not chase, block, stare, or argue. Create distance and call for help if threatened.',
        'Legal placement is not legal attention.',
        'The exam may describe a mounted phone but then add repeated taps, reading, video, or a young driver — facts that change the answer.',
      ]),
      rule('Your condition is part of safety', [
        'Angry, sick, dizzy, or exhausted? Do not drive until you can focus.',
        'Illness, strong emotion, poor sleep, vision changes, and medicine can reduce judgment or reaction.',
        'Read medicine warnings and ask a professional when effects are unclear.',
        'Avoid covering both ears with a headset or earplugs while driving.',
      ]),
    ],
    test: [
      q('How should you handle the long phone interaction?', ['Hold the phone closer to the wheel', 'Wait until safely parked', 'Complete the interaction because the phone is mounted'], 1, 'Permitted mounting does not make prolonged interaction lawful or attentive.', { image: 'distraction-and-fatigue-a01' }),
      q('May a driver read or type a message on a handheld phone while driving?', ['Yes, with hazard lights', 'No', 'Yes, at low speed'], 1, 'Reading or typing on a handheld phone while driving is prohibited.', { image: 'distraction-and-fatigue-a01' }),
      q('Which phone use is the safest while the vehicle is moving?', ['A hands-free setup prepared before the trip', 'Typing an address while moving', 'Watching a video'], 0, 'Set the phone up before moving; any interaction that takes your eyes or mind from the road is unsafe.', { image: 'distraction-and-fatigue-a02' }),
      q('May a driver under {{phone.minorNoDeviceAge}} make an ordinary hands-free call while driving in {{state}}?', ['No', 'Yes, because it is hands-free', 'Yes, with an adult passenger'], 0, 'The under-{{phone.minorNoDeviceAge}} restriction includes hands-free use except for emergencies.', { image: 'distraction-and-fatigue-a03' }),
      q('You are fighting sleep and missing roadway information. What is the correct response?', ['Open another app', 'Drive faster to arrive sooner', 'Stop driving at a safe place'], 2, 'Do not continue when fatigue prevents alert observation and safe control.', { image: 'distraction-and-fatigue-a03' }),
      q('A prescription label warns that the medicine may cause drowsiness. What is the safest choice?', ['Drive faster so the trip is shorter', 'Do not drive until you know you can do so safely', 'Drink coffee and ignore the warning'], 1, 'Medication can impair driving. Follow the warning and do not drive until its effects are understood and safe.'),
    ],
  }),

  lesson('alcohol-drugs-dui', {
    title: 'Alcohol, Drugs, and Medication',
    objective: 'A legal substance can still make driving unsafe and illegal.',
    keyPoints: ['Plan a sober ride.', 'Know the {{state}} BAC rules.', 'Treat medicine warnings seriously.'],
    challenge: challenge(
      'A prescription warns that it may cause drowsiness.',
      'What should you do?',
      ['Drive and test the effect', 'Wait until driving is safe', 'Add an energy drink'],
      1,
      'Do not drive until you understand the effect and can drive safely.',
      { image: 'alcohol-drugs-dui-a01' },
    ),
    cards: [
      why('Impairment starts before you feel drunk', [
        'Judgment and reaction can change early. Feeling normal is not proof of safe driving.',
        'It is unlawful to drive while under the influence of alcohol, a drug, or their combined influence.',
        'Prescription or legal status does not excuse impaired control. If a substance prevents safe driving, do not drive.',
      ]),
      rule('Time removes alcohol', [
        'Coffee, food, air, and showers do not sober you quickly. Plan another ride.',
        'Never calculate a “safe number of drinks.” Body response varies, and no formula converts drinks into permission to drive.',
        'Plan a sober ride before drinking, while your judgment is still yours.',
      ]),
      rule('Know the {{state}} BAC lines', [
        'The adult per se limit is {{bac.adult}}%: at that level you are guilty of driving under the influence even without visible impairment.',
        'Under {{bac.under21Age}}, {{state}} sets the line at {{bac.under21}}% — effectively zero tolerance.',
        'Read the age and status facts in a question before choosing a number.',
        'Impairment below the number is still an offense.',
      ]),
      recall('Recall · BAC limit', 'The adult per se limit in {{state}} is [[{{bac.adult}}%]] — and impairment below it is still an [[offense]].'),
      rule('Cannabis can impair driving', [
        'Legal purchase does not make impaired driving legal.',
        'Using cannabis with alcohol or another drug can increase impairment.',
        'Judgment, attention, vision, coordination, and reaction can worsen before a person notices.',
        'Combining substances can make the effect stronger and less predictable.',
      ]),
      recall('Recall · Under {{bac.under21Age}}', 'Under {{bac.under21Age}}, the line is [[{{bac.under21}}%]] — effectively zero tolerance.'),
      rule('Medication counts too', [
        'Read warnings. Ask a professional when the effect is unclear.',
        'Many cold, allergy, sleep, and pain medicines slow reaction or cause drowsiness.',
        'A driver and passengers may not drink alcohol in a motor vehicle on a road.',
        'When the label says “do not operate machinery,” a car is the machinery.',
      ]),
      image('alcohol-drugs-dui-a03'),
      rule('A DUI arrest can trigger chemical testing', [
        'By driving in {{state}}, you agree to chemical testing of your breath or blood after a lawful DUI arrest.',
        'Refusing a required test has consequences separate from the DUI case itself.',
        'In {{state}}, a first refusal costs the license for {{refusal.firstSuspension}}.',
      ]),
      rule('Open containers have their own rules', [
        'An open container of alcohol never rides in the passenger area. The trunk is the right place.',
        'The reliable plan is made before impairment starts: a sober driver, transit, a taxi, or a rideshare.',
        'Never ride with a driver you believe is impaired.',
      ]),
      recall('Recall · Open containers', 'An open container never rides in the [[passenger area]] — use the [[trunk]].'),
      remember('Make the decision before using', [
        'Do not negotiate after impairment starts.',
        'DUI questions become easier when you separate impairment, status-based BAC rules, chemical testing, and container rules.',
        'A number can prove a specific violation; it never guarantees that the person is safe to drive.',
      ]),
      recall('Recall · Implied consent', 'By driving in {{state}}, you consent to [[chemical testing]] after a lawful DUI arrest.'),
    ],
    test: [
      q('The driver is below {{bac.adult}}% but clearly impaired. Can the driver still be arrested for DUI?', ['Only if a passenger complains', 'Yes, impairment can establish DUI without reaching {{bac.adult}}%', 'No, {{bac.adult}}% is permission to drive'], 1, 'Driving while impaired by alcohol, drugs, or both is unlawful independently of the {{bac.adult}}% per se rule.', { image: 'alcohol-drugs-dui-a01' }),
      q('Does a valid prescription allow driving while the medicine impairs control?', ['Only at night', 'No', 'Yes'], 1, 'The DUI impairment rule applies to drugs regardless of whether possession was lawful.', { image: 'alcohol-drugs-dui-a01' }),
      q('Which BAC threshold is tied to the adult per se driving offense in {{state}}?', ['Twice the posted limit', '{{bac.adult}}%', 'Any measurable amount'], 1, 'The adult per se threshold is {{bac.adult}}%.', { image: 'alcohol-drugs-dui-a01' }),
      q('What happens to your license after a first refusal of a required chemical test in {{state}}?', ['It is suspended for {{refusal.firstSuspension}}', 'Nothing, refusal has no consequence', 'It is suspended for one week'], 0, 'A first refusal brings a suspension of {{refusal.firstSuspension}}; prior events can bring longer periods.', { image: 'alcohol-drugs-dui-a03' }),
      q('Is an opened alcohol container generally allowed beside the driver on a road?', ['No', 'Yes, if the driver is sober', 'Yes, below the speed limit'], 0, 'The open-container restriction is separate from whether the driver appears impaired.', { image: 'alcohol-drugs-dui-a03' }),
      q('Can a legally prescribed medicine still make it illegal or unsafe to drive?', ['No, prescriptions never impair driving', 'Yes, if it impairs the ability to drive safely', 'Only when mixed with coffee'], 1, 'A prescription does not make impaired driving safe or legal.'),
    ],
  }),

  lesson('seat-belts-child-safety', {
    title: 'Protect Everyone in the Car',
    objective: 'Belts, child restraints, airbags, and supervision work together.',
    keyPoints: ['Buckle every occupant.', 'Use the correct child restraint.', 'Never leave a child in danger.'],
    challenge: challenge(
      'A car has airbags.',
      'Does everyone still need a seat belt?',
      ['Yes', 'Only front passengers', 'Only at freeway speed'],
      0,
      'Airbags support seat belts. They do not replace them.',
      { image: 'seat-belts-child-safety-a01' },
    ),
    cards: [
      rule('Seat belts work on every trip', [
        'Buckle before the car moves. The driver is responsible for passengers who must be restrained.',
        'Drivers and passengers must be properly restrained by an available safety belt, subject to legal exceptions.',
        'A short trip, low speed, or a rear seat does not make an unrestrained occupant safe.',
      ]),
      rule('Wear the belt correctly', [
        'Place the lap belt low across the hips. Keep the shoulder belt across the chest.',
        'An airbag is designed to work with correct seating and restraint.',
        'Sit upright and keep a safe distance from the airbag cover.',
        'Use the rear seat and the correct child restraint for young passengers.',
      ]),
      visual('Airbags are extra protection', [
        'Sit upright and keep space from the cover. Never rely on an airbag alone.',
        'Occupant rules protect people who cannot rely on the vehicle alone.',
        'Solve child questions from the facts provided: age, height, weight, seat, restraint, and any genuine legal exception.',
      ]),
      related('Children move through restraint stages', [
        'Use a seat that fits the child and the manufacturer instructions. The back seat is the safest place.',
        'In {{state}}, a child under {{child.restraintAge}} must ride in a child restraint appropriate for age and size.',
        'A child at least {{child.beltHeight}} tall may use a properly fitted safety belt instead.',
        'The law has medical, size, and seating exceptions; do not invent one from convenience.',
      ]),
      recall('Recall · Child restraints', 'A child under [[{{child.restraintAge}}]] rides in a child restraint; at [[{{child.beltHeight}}]] the seat belt alone is allowed.'),
      image('seat-belts-child-safety-a03'),
      rule('Rear-facing protects the youngest children', [
        'Infants and toddlers ride rear-facing as long as the seat allows, because it supports the head and neck in a frontal crash.',
        'Age is important, but it may not be the only fact. Height and weight limits of the seat matter too.',
        'Never place a rear-facing seat in front of an active airbag.',
      ]),
      rule('A parked car can become deadly', [
        'Heat rises fast. Do not leave a child where heat or controls create danger.',
        'Heat, controls, windows, and traffic make an unattended vehicle unsafe for children and dependent people.',
        'Check the entire vehicle before locking it.',
        'Secure pets so they do not distract the driver or enter a dangerous area.',
      ]),
      recall('Recall · Children alone', 'Never leave a young child [[alone]] in a car — especially with the engine on or the [[keys]] inside.'),
    ],
    test: [
      q('What should guide the decision?', ['The child’s preference', 'The child-restraint age, size, seating, and exception rules', 'Height alone'], 1, 'Child restraint questions require the complete age, size, rear-seat, and exception framework.', { image: 'seat-belts-child-safety-a01' }),
      q('Does a short neighborhood trip remove the normal seat-belt duty?', ['Yes', 'Only for rear passengers', 'No'], 2, 'Trip length does not cancel the ordinary restraint requirement.', { image: 'seat-belts-child-safety-a01' }),
      q('Where should a child under {{child.restraintAge}} generally be restrained in {{state}}?', ['In an appropriate child restraint, in the back seat', 'Unrestrained in front', 'Standing behind the driver'], 0, 'The general rule places a child under {{child.restraintAge}} in an appropriate restraint, and the back seat is the safest place.', { image: 'seat-belts-child-safety-a01' }),
      q('Why do the youngest children ride rear-facing?', ['It is easier to reach them', 'It supports the head and neck in a frontal crash', 'It is required only on freeways'], 1, 'A rear-facing seat spreads crash forces across the back and supports the head and neck.', { image: 'seat-belts-child-safety-a03' }),
      q('Why is a parked car dangerous for a child left inside?', ['The radio may turn on', 'Heat rises fast and controls can be reached', 'The seat belt may lock'], 1, 'A parked car heats quickly, and a child can reach controls or be trapped by windows and locks.', { image: 'seat-belts-child-safety-a03' }),
      q('What is the relationship between an airbag and a seat belt?', ['The airbag replaces the seat belt', 'The airbag supplements a correctly worn seat belt', 'Only rear-seat passengers need belts'], 1, 'Airbags are supplemental protection and are designed to work with seat belts.'),
    ],
  }),

  lesson('equipment-loads-towing', {
    title: 'Is Your Car Ready?',
    objective: 'A short check can catch a dangerous problem before the trip.',
    keyPoints: ['Check safety equipment.', 'Secure every load.', 'Allow more room when towing.'],
    challenge: challenge(
      'A loose object can roll under the brake pedal.',
      'What should you do?',
      ['Leave it on the floor', 'Secure it before driving', 'Move it while driving'],
      1,
      'Nothing should block the pedals or driver’s view.',
      { image: 'equipment-loads-towing-a01' },
    ),
    cards: [
      why('Walk around the car', [
        'Look for tire damage, leaks, obstacles, and people nearby. Check before moving.',
        'A roadworthy vehicle lets the driver see, stop, communicate, grip the road, and keep everything inside it.',
        'Equipment questions are easier when grouped by the failure each rule prevents.',
      ]),
      rule('Make sure you can see', [
        'Windows, mirrors, lights, and wipers must work. Remove anything blocking the view.',
        'You do not need a workshop inspection before every trip, but safety-critical items must work.',
        'Check lights, mirrors, windows, wipers, brakes, horn, and seat position.',
        'Make sure loose objects cannot roll under pedals or block your view.',
      ]),
      rule('Controls must work too', [
        'Check brakes, horn, steering, and warning lights. Do not ignore a safety problem.',
        'In {{state}}, the horn must be audible under normal conditions from at least {{equipment.hornFeet}} feet.',
        'Tires need tread to grip in rain: {{state}} sets the legal minimum at {{equipment.treadInches}} inch in two adjacent grooves.',
        'Replace tires before the grooves wear away, and keep them at the pressure printed on the door label.',
        'A dashboard warning light is a reason to check, not to guess.',
      ]),
      recall('Recall · Tire tread', 'The minimum tire tread is [[{{equipment.treadInches}} inch]] in two adjacent grooves.'),
      rule('Cargo must stay with the vehicle', [
        'Secure it against shifting, falling, leaking, or blowing out. Stop safely and recheck the load during a long trip.',
        'Construct, cover, or secure a load so contents do not drop, sift, leak, blow, spill, or escape.',
        'Recheck straps after the vehicle has moved and keep loose material contained.',
        'A cover is useful only when it actually prevents the load from escaping.',
      ]),
      recall('Recall · Equipment', 'Your horn must be audible from at least [[{{equipment.hornFeet}} feet]].'),
      rule('Keep every load secure and visible', [
        'Secure cargo before the vehicle moves. Do not let a load hide your lights, plate, mirrors, or view.',
        'The vehicle must have the mirrors required for its configuration, including a driver-side mirror.',
        'A camera can help, but it does not legalize an obstructed view or replace a required mirror.',
        'Towing changes the drive: allow more stopping room, turn wider, and check mirrors often.',
      ]),
      image('equipment-loads-towing-a03'),
      rule('Passengers and pets need protection', [
        'Keep people out of open load areas. Riding in a pickup bed is restricted by law and unsafe at any speed.',
        'Animals in a load space must be protected from falling, jumping, or being thrown out, by an enclosure or a secured restraint.',
        'Pets inside the car belong in a carrier or harness, never loose where they can jump or distract you.',
        'Smooth acceleration and braking, correct tire pressure, and less idling also save fuel.',
      ]),
    ],
    test: [
      q('Which problem can be ignored for a short trip?', ['The load', 'The tire', 'None of them'], 2, 'Visibility, tire condition, and secure-load rules apply before the vehicle enters the road.', { image: 'equipment-loads-towing-a01' }),
      q('May a large object hang from the mirror and block the road view?', ['Yes, if decorative', 'Only on local roads', 'No'], 2, 'Prohibited objects may not obstruct the driver’s required view.', { image: 'equipment-loads-towing-a01' }),
      q('From what distance must the horn be audible under normal conditions in {{state}}?', ['At least {{equipment.hornFeet}} feet', 'At least one mile', 'Only from inside the car'], 0, 'The horn must be heard from at least {{equipment.hornFeet}} feet.', { image: 'equipment-loads-towing-a01' }),
      q('A tarp is present but loose material can still blow out. Is the load secured?', ['Yes, any tarp is enough', 'Only if driving slowly', 'No'], 2, 'The result must prevent escape; a cover that fails that job is not enough.', { image: 'equipment-loads-towing-a03' }),
      q('You tow a trailer for the first time. What changes?', ['Nothing, if the trailer is light', 'Longer stopping distances and wider turns', 'You may use the carpool lane'], 1, 'Towing adds weight and length: leave more stopping room, turn wider, and check the mirrors often.', { image: 'equipment-loads-towing-a03' }),
      q('What is the safest way to carry loose objects inside a vehicle?', ['Place them near the pedals', 'Secure them so they cannot move or block controls', 'Stack them above the driver’s line of sight'], 1, 'Loose objects can interfere with controls or become dangerous in a sudden stop.'),
    ],
  }),
];
