// California state lessons — module 8 "Pass the California Test".
// Every number here is backed by the catalog rules listed on each lesson.
import {
  lesson,
  why,
  rule,
  related,
  remember,
  trap,
  visual,
  image,
  recall,
  challenge,
  q,
} from '../../skeleton/helpers.mjs';

export const LESSONS = {
  'pass-the-test': [
    lesson('permit-and-knowledge-test', {
      title: 'Permit and Knowledge Test',
      objective: 'The permit process checks knowledge, vision, identity, and safe supervision.',
      keyPoints: ['Know the basic application flow.', 'Use a permit only with supervision.', 'Understand the three-attempt rule.'],
      rules: [
        'CA_VEH_12509_INSTRUCTION_PERMIT',
        'CA_DMV_KNOWLEDGE_PASSING_SCORE',
        'CA_DMV_KNOWLEDGE_TEST_ATTEMPTS',
        'CA_CCR_T13_20_03_VISION_STANDARD',
        'CA_HANDBOOK_MEDICAL_REPORTING',
      ],
      challenge: challenge(
        'You have an instruction permit but no qualified supervisor.',
        'May you practice alone?',
        ['Yes, on quiet roads', 'No', 'Only during daylight'],
        1,
        'An instruction permit does not allow solo driving.',
        { image: 'permits-provisional-licenses-a01' },
      ),
      cards: [
        why('The application starts the process', [
          'DMV checks identity, eligibility, and the required documents.',
          'Each stage confirms a different kind of readiness.',
          'The knowledge test checks rules and safe-driving decisions. The permit and the drive test add supervised practice and demonstrated vehicle control.',
        ]),
        rule('Vision is part of the test', [
          'The ordinary vision screening standard is 20/40 with both eyes together.',
          'Another passing result is 20/40 in one eye and at least 20/70 in the other; the regulation also offers an alternative examination and drive-test pathway.',
          'Health counts too: doctors must report drivers 14 and older whose conditions can affect safe driving, such as a lapse of consciousness.',
          'A report is not an automatic loss. DMV can reexamine and decide.',
        ]),
        recall('Recall · Vision screening', 'The vision screening standard is [[20/40]] with both eyes together.'),
        image('permits-provisional-licenses-a02'),
        rule('California allows three attempts', [
          'DMV publishes an 80% passing score for the knowledge test.',
          'An applicant has three attempts for each required knowledge test.',
          'Failing the same test three times invalidates the application; you must reapply and pay the fees again.',
          'Do not assume a fourth attempt appears automatically.',
        ]),
        recall('Recall · Knowledge test', 'You get [[three]] attempts per application. DMV publishes an [[80%]] passing score.'),
        rule('Study the decision, not the letter', [
          'The knowledge test checks how you apply rules to driving decisions.',
          'Study signs, laws, and real road situations. Learn why an answer is correct instead of memorizing answer letters.',
          'After a failed test, read the instructions DMV gives you before scheduling again, and use the eligibility date in your own record.',
          'Bring the required documents, proof of identity, and the completed application; a missing document ends the visit before the test starts.',
        ]),
        recall('Recall · Medical fitness', 'Conditions like a lapse of [[consciousness]] are reported to [[DMV]], which can reexamine a driver.'),
        image('permits-provisional-licenses-a03'),
        rule('A permit requires supervision', [
          'You can generally get a noncommercial Class C instruction permit at age 15½.',
          'You may practice only with the supervision required by the permit. It is not an unrestricted license.',
          'The supervisor sits beside you, holds a valid license, and is close enough to take control if needed.',
          'Exam strategy: read the whole situation and choose the safest legal action, not the fastest one.',
        ]),
      ],
      test: [
        q('What is the minimum age for an ordinary Class C instruction permit?', ['18', '15½', '14'], 1, 'California issues the ordinary instruction permit from age 15½.', { image: 'permits-provisional-licenses-a01' }),
        q('What happens after failing the same required knowledge test three times?', ['The vision test is waived', 'The application becomes invalid and the person must reapply', 'A fourth attempt is automatic'], 1, 'The three-attempt rule requires reapplication after the third failure.', { image: 'permits-provisional-licenses-a03' }),
        q('What passing score does DMV publish for the knowledge test?', ['80%', '50%', '100%'], 0, 'DMV publishes an 80 percent passing score.'),
        q('What must happen before practice with an instruction permit?', ['The permit must be valid and supervision must meet the rule', 'The driver may practice alone', 'Only insurance matters'], 0, 'Practice starts only with a valid permit and qualifying supervision.'),
        q('Why does DMV screen vision?', ['To confirm safe visual ability', 'To set insurance prices', 'To choose a vehicle'], 0, 'Vision is part of the licensing safety check.'),
        q('A doctor reports a driver’s lapse of consciousness to DMV. What follows?', ['Automatic permanent revocation', 'DMV can reexamine the driver and decide', 'Nothing; doctors cannot report'], 1, 'Physicians must report qualifying conditions; DMV then reexamines and decides.'),
      ],
    }),

    lesson('drivers-under-18', {
      title: 'Rules for Drivers Under 18',
      objective: 'California adds training and first-year limits for new drivers under 18.',
      keyPoints: ['Complete every training gate.', 'Track supervised practice.', 'Know first-year restrictions.'],
      rules: [
        'CA_VEH_12509_INSTRUCTION_PERMIT',
        'CA_VEH_12814_6_PROVISIONAL_ELIGIBILITY',
        'CA_VEH_12814_6_PROVISIONAL_RESTRICTIONS',
      ],
      challenge: challenge(
        'A minor has held a permit for three months and completed practice hours.',
        'Is the six-month holding rule complete?',
        ['Yes', 'No', 'Only if the test is easy'],
        1,
        'The practice hours do not replace the minimum permit-holding period.',
        { image: 'drivers-under-18-ca-permits-provisional-licenses-a01' },
      ),
      cards: [
        rule('The permit has a minimum age', [
          'California’s ordinary Class C instruction permit begins at 15½.',
          'Reaching the minimum age does not remove the other permit requirements: the application, the knowledge test, and enrollment in driver education.',
          'You may practice only with the supervision required by the permit — a licensed parent, guardian, adult 25 or older, or instructor in the seat beside you.',
        ]),
        rule('Education and training are separate gates', [
          'Complete every required part. One does not automatically replace another.',
          'Count the six months from the correct permit date, and keep a record of your practice hours.',
          'A minor generally has to meet all four requirements:',
        ], { bullets: ['Be at least 16.', 'Complete driver education and training.', 'Hold the permit for at least six months.', 'Record 50 practice hours, including 10 at night.'] }),
        recall('Recall · Permit basics', 'The instruction permit starts at age [[15½]]. Hold it for at least [[six months]].'),
        image('drivers-under-18-ca-permits-provisional-licenses-a02'),
        rule('The provisional license starts another stage', [
          'Passing the drive test does not remove every restriction.',
          'Special restrictions continue during the first year of a provisional license.',
          'Bring the completed driver education and training certificates and the signed practice log to the drive test; without them the appointment is wasted.',
          'Each stage confirms a different kind of readiness: the knowledge test checks decisions, the permit adds supervised practice, the drive test shows vehicle control.',
        ]),
        recall('Recall · Practice hours', 'Record [[50]] supervised practice hours, including [[10]] at night.'),
        image('drivers-under-18-ca-permits-provisional-licenses-a03'),
        rule('Night driving and passengers are restricted', [
          'During the first 12 months of a provisional license, a driver under 18 generally may not drive from 11 p.m. to 5 a.m.',
          'The driver also may not carry passengers under 20 without qualifying supervision.',
          'Qualifying supervision means a licensed parent or guardian, a licensed driver age 25 or older, or a licensed or certified driving instructor.',
          'Medical, school, employment, and immediate-family necessity exceptions require specified documentation.',
        ]),
        recall('Recall · First 12 months', 'First 12 months: no driving [[11 p.m.]]–5 a.m., and passengers under [[20]] need qualifying supervision.'),
        remember('Start with the stage', [
          'Ask which licensing stage the question describes: permit, provisional first year, or full license.',
          'Then apply that stage’s age, time, practice, or passenger rule.',
          'A correct number attached to the wrong stage is still a wrong answer.',
          'The restrictions end by time, not by good behavior: 12 months after the provisional license, or at 18, whichever comes first.',
        ]),
      ],
      test: [
        q('Is the applicant ready for provisional licensing?', ['Yes, age alone is enough', 'Yes, if the knowledge score was perfect', 'No, the permit must generally be held for at least six months'], 2, 'Minor provisional eligibility includes the six-month permit-holding requirement and other conditions.', { image: 'drivers-under-18-ca-permits-provisional-licenses-a01' }),
        q('How many of the 50 practice hours must be at night?', ['20', '10', '5'], 1, 'The requirement includes 10 night hours within 50 total practice hours.', { image: 'drivers-under-18-ca-permits-provisional-licenses-a02' }),
        q('During the first 12 months, which time range is generally restricted?', ['Noon to 2 p.m.', '11 p.m. to 5 a.m.', '8 p.m. to 8 a.m.'], 1, 'The provisional time restriction is generally 11 p.m. to 5 a.m.', { image: 'drivers-under-18-ca-permits-provisional-licenses-a03' }),
        q('How long must a minor generally hold the permit before provisional licensing?', ['At least six months', 'A few days', 'Thirty days'], 0, 'California generally requires at least six months.'),
        q('How many verified supervised practice hours are generally required?', ['50, including 10 at night', '10 total', '100, all at night'], 0, 'The verified requirement is 50 hours, including 10 at night.'),
        q('During the first 12 months, may a provisional driver ignore passenger restrictions with friends?', ['No', 'Yes, with permission from a friend', 'Yes, during daylight'], 0, 'The first-year restrictions apply unless a legal exception or qualifying supervision exists.'),
      ],
    }),

    lesson('licenses-and-registration', {
      title: 'License, Registration, and Vehicle Transfer',
      objective: 'Different events create different people, forms, and deadlines.',
      keyPoints: ['Carry a valid license.', 'Match each deadline to the event.', 'Keep proof of submissions.'],
      rules: [
        'CA_VEH_12500_LICENSE_REQUIRED',
        'CA_VEH_12951_LICENSE_POSSESSION',
        'CA_VEH_14600_ADDRESS_CHANGE',
        'CA_VEH_5900_SELLER_TRANSFER_NOTICE',
        'CA_VEH_5902_BUYER_TRANSFER_APPLICATION',
        'CA_VEH_4152_5_6700_NEW_RESIDENT_REGISTRATION',
        'CA_VEH_516_RESIDENCY',
      ],
      challenge: challenge(
        'You sold a California vehicle.',
        'Who reports the sale or release of liability?',
        ['The seller', 'Only the buyer', 'The insurance company'],
        0,
        'The seller has a separate reporting duty.',
        { image: 'licenses-and-registration-a01' },
      ),
      cards: [
        rule('Driving requires a valid license', [
          'You must not drive on a California highway without a valid license or an applicable legal exemption.',
          'Keep the valid license in immediate possession while driving and present it on lawful demand.',
          'A photo of the license on a phone is not the license; carry the card or the official digital credential where it is accepted.',
        ]),
        rule('Address change: 10 days', [
          'Notify DMV of a new residence or mailing address within 10 days. Keep the confirmation.',
          'This duty is separate from vehicle registration, ownership transfer, or license renewal.',
          'Notices about renewals, suspensions, and hearings go to the address on file — a stale address can cost you a deadline you never saw.',
        ]),
        image('licenses-and-registration-a02'),
        rule('Seller: 5 days. Buyer: 10 days', [
          'After transferring ownership and possession, the seller notifies DMV within five calendar days. This does not complete the buyer’s job.',
          'A buyer who receives a properly endorsed ownership certificate applies for the transfer within 10 days.',
          'A license shows the driving privilege; registration connects a vehicle to its operating record; the title records ownership.',
        ]),
        rule('New registration: 20 days', [
          'When an out-of-state vehicle becomes subject to California registration because of residency or gainful employment, apply within 20 days.',
          'Do not wait for the old registration to expire.',
          'Five, 10, and 20 days are all correct California numbers for different events. Identify the event before choosing the number.',
        ]),
        recall('Recall · DMV deadlines', 'Address change: [[10 days]]. Seller’s notice: [[5 days]]. New California registration: [[20 days]].'),
        image('licenses-and-registration-a03'),
        rule('Residency is more than one address', [
          'Vehicle-registration residency turns on intent to live or remain in California beyond a temporary basis.',
          'Presence for at least six months in a 12-month period creates a rebuttable presumption, but other evidence can establish residency.',
          'A temporary visit does not automatically make someone a California resident.',
        ]),
        recall('Recall · Residency', 'Six months of presence in a 12-month period creates a presumption of [[residency]].'),
        remember('Match each deadline to the event', [
          'First identify who must act and what changed. A number is useful only when it matches the correct event.',
          'The person responsible for a filing acts immediately instead of waiting for another party.',
          'Keep the three deadlines separate:',
        ], { bullets: ['A seller reports the transfer within 5 calendar days.', 'An address change or a buyer transfer uses a 10-day deadline.', 'New California registration uses a 20-day deadline.'] }),
      ],
      test: [
        q('Which clock applies to the registration application?', ['One year', '20 days after the California duty is triggered', 'Five calendar days'], 1, 'An out-of-state vehicle newly subject to California registration has a 20-day application deadline.', { image: 'licenses-and-registration-a01' }),
        q('Where must a licensed driver keep the valid license while driving?', ['In immediate possession', 'At home', 'Only in a digital photo'], 0, 'The possession rule requires the valid license to be immediately available while driving.', { image: 'licenses-and-registration-a01' }),
        q('How long does a driver have to notify DMV of a new address?', ['20 days', '10 days', '5 days'], 1, 'The address-change deadline is 10 days.', { image: 'licenses-and-registration-a02' }),
        q('Is six months the only possible proof of California residency?', ['No, it creates a rebuttable presumption and other evidence may apply', 'Yes', 'Only for minors'], 0, 'The six-month condition is a presumption, not the exclusive residency test.', { image: 'licenses-and-registration-a03' }),
        q('Which deadline belongs to the seller’s DMV transfer notice?', ['20 days', 'Five calendar days', '10 days'], 1, 'The seller’s notice deadline is five calendar days; the buyer’s application deadline is 10 days.', { image: 'licenses-and-registration-a03' }),
        q('After a private-party vehicle sale in California, who has a separate DMV filing duty?', ['Only the buyer', 'Both seller and buyer have their own filing duties', 'Only the insurance company'], 1, 'The seller reports the transfer, while the buyer applies to transfer ownership.'),
      ],
    }),

    lesson('penalties-and-points', {
      title: 'Points, Penalties, and Police Stops',
      objective: 'The final questions often test consequences, not just driving moves.',
      keyPoints: ['Separate one- and two-point events.', 'Know the 4/6/8 pattern.', 'Make traffic stops predictable.'],
      rules: [
        'CA_VEH_12810_POINT_VALUES',
        'CA_VEH_12810_5_NEGLIGENT_OPERATOR',
        'CA_VEH_23575_IGNITION_INTERLOCK',
        'CA_DMV_KNOWLEDGE_TEST_ATTEMPTS',
        'CA_VEH_13353_TEST_REFUSAL',
      ],
      challenge: challenge(
        'An officer activates emergency lights behind you.',
        'What should you do first?',
        ['Accelerate', 'Signal and pull over safely', 'Stop in the active lane when a shoulder is open'],
        1,
        'Choose a safe place, stop, and follow instructions.',
        { image: 'penalties-and-points-a01' },
      ),
      cards: [
        rule('Not every conviction has the same points', [
          'California assigns two points to specified serious convictions such as hit-and-run, DUI, and reckless driving.',
          'Other traffic convictions involving safe vehicle operation generally receive one point unless an exception applies.',
          'A collision you are responsible for can also receive one point.',
        ]),
        rule('Remember the 4/6/8 pattern', [
          'For an ordinary Class C driver, the pattern is 4 points in 12 months, 6 in 24, or 8 in 36.',
          'Reaching one of these levels creates a legal presumption that the driver is a negligent operator.',
          'The law provides for DMV consideration and a hearing; do not rewrite the threshold as an automatic permanent revocation.',
          'Memorize the three thresholds:',
        ], { bullets: ['Four points in 12 months.', 'Six in 24.', 'Eight in 36.'] }),
        recall('Recall · 4/6/8', 'The negligent-operator thresholds: [[4]] points in 12 months, [[6]] in 24, [[8]] in 36.'),
        image('penalties-and-points-a02'),
        rule('Different events trigger different actions', [
          'Three failed attempts invalidate the current knowledge-test application.',
          'A first chemical-test refusal carries its own administrative suspension.',
          'A reportable uninsured collision can start suspension procedures, and provisional restrictions depend on age and license timing.',
          'Do not mix these consequences.',
        ]),
        recall('Recall · DUI points', 'A DUI conviction carries [[two]] points, not one.'),
        rule('DUI and hit-and-run bring more than points', [
          'Criminal, licensing, insurance, and financial consequences can overlap. Read the exact offense.',
          'A DUI can also bring an ignition interlock device: a breath tester wired to the starter. No clean sample, no start.',
          'Insurance cost and eligibility can change, and serious conduct can bring criminal penalties beyond an ordinary infraction.',
        ]),
        rule('Start a traffic stop safely', [
          'Signal and move to a safe place. Stop the vehicle and stay calm.',
          'Remain in the vehicle unless directed otherwise, and turn on the interior light at night.',
          'Keep your hands where they can be seen and explain before reaching for documents.',
          'A safe, predictable stop protects both the driver and the officer.',
        ]),
        image('penalties-and-points-a03'),
        rule('Never flee', [
          'Evading an officer is a crime; evading that causes serious bodily injury can bring imprisonment.',
          'A safe stop is always the correct first move.',
          'Distractors often use words like always, never, automatic, or immediately while omitting a condition.',
          'Before choosing an exam answer, identify each condition:',
        ], { bullets: ['The driver involved', 'The type of road', 'The time window', 'The signal shown', 'Any stated exception'] }),
        recall('Recall · Traffic stops', 'Pulled over? Stop in a safe place, remain in the [[vehicle]], and keep your [[hands]] visible.'),
        remember('Final exam method', [
          'Final review is about conditions, not slogans.',
          'Penalties, points, suspensions, and exam numbers often look familiar; the correct answer connects each consequence to the exact violation, driver status, time window, and procedure.',
          'Use the same method on each exam question:',
        ], { bullets: ['Name the situation.', 'Remove unsafe answers.', 'Apply the California rule and the exact condition.'] }),
      ],
      test: [
        q('What does the 4/6/8 rule actually establish?', ['No consequence at all', 'A prima facie negligent-operator presumption, with DMV process and hearing', 'An automatic permanent revocation'], 1, 'The 4/6/8 thresholds create a prima facie negligent-operator presumption rather than an automatic permanent loss.', { image: 'penalties-and-points-a01' }),
        q('Which value applies to a DUI conviction under the point rule?', ['One point', 'Zero points in every case', 'Two points'], 2, 'California assigns two points to a DUI conviction.', { image: 'penalties-and-points-a01' }),
        q('Which point total matches the 24-month negligent-operator threshold?', ['Four', 'Eight', 'Six'], 2, 'The sequence is 4 in 12, 6 in 24, and 8 in 36 months.', { image: 'penalties-and-points-a02' }),
        q('Which event invalidates the knowledge-test application?', ['Receiving one point', 'Failing the same required test three times', 'One incorrect practice answer'], 1, 'The application consequence follows the third failed attempt for the same required test.', { image: 'penalties-and-points-a03' }),
        q('An answer gives the correct number but applies it to the wrong driver status. Is it correct?', ['Only if it is the longest option', 'No', 'Yes, numbers always control'], 1, 'A rule’s condition is part of the rule; the number alone is insufficient.', { image: 'penalties-and-points-a03' }),
        q('An officer activates emergency lights behind you. What is the safest first response?', ['Accelerate until you find your destination', 'Signal and pull over safely, then follow instructions', 'Stop immediately in the active traffic lane when a shoulder is available'], 1, 'Signal, choose a safe stopping place, stop, and make your actions predictable.'),
      ],
    }),
  ],
};
