// Texas state lessons — module 8 "Pass the Texas Test".
// Every number here is backed by the catalog rules listed on each lesson.
import {
  lesson,
  why,
  rule,
  related,
  remember,
  trap,
  visual,
  image,
  recall,
  challenge,
  q,
} from '../../skeleton/helpers.mjs';

export const LESSONS = {
  'pass-the-test': [
    lesson('permit-and-knowledge-test', {
      title: 'Learner License and Knowledge Test',
      objective: 'The learner license process checks driver education, knowledge, vision, and safe supervision.',
      keyPoints: ['Know the basic application flow.', 'Use a learner license only with a supervisor.', 'Know what the test covers.'],
      rules: [
        'TX_TN_521_222_LEARNER_LICENSE',
        'TX_TN_521_1601_DRIVER_EDUCATION_UNDER_25',
        'TX_TN_521_161_EXAMINATION',
        'TX_HANDBOOK_KNOWLEDGE_TEST_AND_ITD',
      ],
      challenge: challenge(
        'You have a learner license but no qualified supervisor in the car.',
        'May you practice alone?',
        ['Yes, on quiet roads', 'No', 'Only during daylight'],
        1,
        'A Texas learner license works only with a licensed driver who is at least 21, with a year of experience, in the seat beside you.',
        { image: 'permit-and-knowledge-test-shared-01' },
      ),
      cards: [
        why('The application starts the process', [
          'The Department of Public Safety checks identity, eligibility, and the required documents.',
          'Driver education comes first: everyone under 25 must complete an approved course before a Texas license is issued. Applicants 18 and older may take the adult course.',
          'Each stage confirms a different kind of readiness: the knowledge test checks decisions, the learner license adds supervised practice, the driving test shows vehicle control.',
        ]),
        rule('Vision is part of the test', [
          'Texas law makes vision the first part of every examination.',
          'The knowledge test covers highway signs in English, Texas traffic laws, your duties toward bicyclists, and how phones and other distractions affect driving.',
          'You may take those parts in writing instead of on a screen.',
          'Study signs, laws, and real road situations. Learn why an answer is correct instead of memorizing answer letters.',
        ]),
        recall('Recall · What the test covers', 'The knowledge test covers [[signs]], traffic laws, duties toward [[bicyclists]], and distraction — after a vision check.'),
        image('permit-and-knowledge-test-shared-01'),
        rule('Texas scores the test at 70 percent', [
          'The handbook sets the passing score at 70 percent. The exam is scheduled within 10 days of your application.',
          'A licensed driver education provider may give its own students the vision, sign, and traffic-law parts.',
          'Before the driving test, every applicant completes the free Impact Texas Drivers video course.',
          'The driving test itself checks ordinary and reasonable control of the vehicle.',
        ]),
        rule('A failed test means another attempt', [
          'Read the instructions the Department of Public Safety gives you before scheduling again, and use the eligibility date in your own record.',
          'Retake the whole knowledge test; there is no partial credit from the first try.',
          'Between attempts, go back to the rule behind each missed question. Most misses are conditions, not facts: who, where, and when.',
        ]),
        recall('Recall · Driver education', 'Everyone under [[25]] completes an approved driver education course before a Texas license; 18 and older may take the [[adult]] course.'),
        image('permit-and-knowledge-test-shared-02'),
        rule('A learner license requires supervision', [
          'A learner license is available from age 15 after the classroom phase of driver education and the knowledge test.',
          'The supervisor must be licensed for the vehicle, at least 21, with at least one year of driving experience, in the seat beside you.',
          'It is not an unrestricted license. Do not practice alone.',
          'Exam strategy: read the whole situation and choose the safest legal action, not the fastest.',
        ]),
        recall('Recall · Learner license', 'Learner license from age [[15]]. Supervisor: licensed, at least [[21]], with a year of experience, in the seat beside you.'),
      ],
      test: [
        q('What is the minimum age for a Texas learner license?', ['15', '16', '14'], 0, 'A learner license may be issued at 15 to an applicant under 18 who has completed the classroom phase of driver education and passed the non-driving parts of the exam.'),
        q('Who may sit beside a learner-license holder as the supervising driver?', ['A licensed driver at least 21 with at least one year of driving experience', 'Any licensed adult in the back seat', 'Any passenger over 18'], 0, 'The supervisor must hold a license for that type of vehicle, be at least 21, have at least one year of driving experience, and occupy the seat beside the operator.'),
        q('Which topics does the Texas knowledge examination cover?', ['Signs, traffic laws, duties toward bicyclists, and distraction', 'Vehicle repair and insurance pricing', 'Only speed limits'], 0, 'Texas law lists highway signs in English, state traffic laws, motorists’ rights and responsibilities toward bicyclists, and the effect of wireless devices and other distractions.'),
        q('What must happen before you practice with a learner license?', ['The license must be in your possession and a qualified supervisor beside you', 'Only a parent’s verbal permission', 'A written route plan'], 0, 'A learner license permits driving only while it is in the holder’s possession and a qualified licensed driver occupies the seat beside the operator.'),
        q('Who must complete a driver education course before receiving a Texas license?', ['Everyone under 25, unless they hold a valid out-of-state license', 'Only drivers under 16', 'Only drivers over 70'], 0, 'No one under 25 receives a Texas license without an approved driver education certificate; applicants 18 and older may take the adult course, and out-of-state license holders are exempt.'),
        q('Why does the Department of Public Safety test vision first?', ['To confirm safe visual ability before any other part of the exam', 'To assign a license class', 'To set the insurance rate'], 0, 'Vision is the first required part of the examination because safe driving depends on seeing signs, signals, and hazards in time.'),
      ],
    }),

    lesson('drivers-under-18', {
      title: 'Rules for Drivers Under 18',
      objective: 'Texas adds driver education, school attendance, and restrictions that last until 18.',
      keyPoints: ['Complete every licensing gate.', 'Hold the learner license six months.', 'Know the under-18 restrictions.'],
      rules: [
        'TX_TN_521_222_LEARNER_LICENSE',
        'TX_TN_521_204_PROVISIONAL_CLASS_C',
        'TX_TN_545_424_UNDER_18_RESTRICTIONS',
        'TX_TN_521_292_SUSPENSION_GROUNDS',
      ],
      challenge: challenge(
        'A 16-year-old has held a learner license for three months and finished driver education.',
        'Is the six-month holding rule complete?',
        ['Yes', 'No', 'Only if the test is easy'],
        1,
        'Finishing driver education does not replace the minimum six months with the learner license.',
        { image: 'signals-q05-asset' },
      ),
      cards: [
        rule('The learner license has a minimum age', [
          'Texas’s learner license begins at 15. Reaching the minimum age does not remove the other requirements.',
          'You need the classroom phase of an approved driver education course, the school-attendance rule, and a pass on every exam part except driving.',
          'You may practice only with a qualified supervisor beside you. It is not an unrestricted license.',
        ]),
        rule('Education and school are separate gates', [
          'Complete every required part. One does not automatically replace another.',
          'Count the six months from the date the learner license was issued, and keep your driver education certificate; the Department of Public Safety needs it.',
          'A minor generally has to meet all of these requirements:',
        ], { bullets: ['Be at least 16.', 'Complete an approved driver education course.', 'Meet the school-attendance rule.', 'Hold the learner license for at least six months.', 'Pass the knowledge and driving tests.'] }),
        recall('Recall · Learner basics', 'The learner license starts at age [[15]]. Hold it for at least [[six months]] before the Class C license.'),
        image('signals-q05-asset'),
        rule('The Class C license starts another stage', [
          'Passing the driving test does not remove every restriction.',
          'Texas keeps the under-18 limits in place until the driver turns 18, however long the license has been held.',
          'School attendance stays a condition: a diploma, at least 80 days of attendance in the previous semester, or 45 days of enrollment in an equivalency program.',
        ]),
        recall('Recall · Class C at 16', 'Class C at [[16]] needs driver education, school attendance, six months on the learner license, and the [[driving test]].'),
        image('drivers-under-18-shared-02'),
        rule('Night, passengers, and phones are restricted', [
          'Until 18, midnight to 5 a.m. is off limits. Work, a school activity, or a medical emergency are the only exceptions.',
          'No more than one passenger under 21 who is not a family member, and no wireless device use at all, even hands-free, except in an emergency.',
          'The night and passenger limits do not apply while a learner is accompanied by the required supervisor.',
        ]),
        recall('Recall · Until 18', 'Until 18: no driving [[midnight]]–5 a.m. except work, school, or emergency; no more than one passenger under [[21]] who is not family.'),
        remember('Start with the stage', [
          'Two moving-violation convictions in 12 months can cost an under-18 driver the license.',
          'Ask which licensing stage the question describes, then apply that stage’s age, time, or passenger rule.',
          'A correct number attached to the wrong stage is still a wrong answer.',
        ]),
      ],
      test: [
        q('A 16-year-old has held a learner license for four months and finished driver education. Is the applicant ready for a Class C license?', ['No, the learner license must be held for at least six months', 'Yes, driver education completes the requirement', 'Yes, at 16 the waiting period ends'], 0, 'Texas issues a Class C license to an applicant under 18 only after the learner license has been held for at least six months, along with driver education, school attendance, and the tests.'),
        q('A 17-year-old with a Class C license wants to drive at 1 a.m. to a friend’s party. Is that allowed?', ['No, driving between midnight and 5 a.m. is restricted except for work, school, or a medical emergency', 'Yes, with a parent’s permission', 'Yes, on any weekend'], 0, 'A driver under 18 may not drive between midnight and 5 a.m. unless the trip is necessary for employment, a school-related activity, or a medical emergency.'),
        q('How many non-family passengers under 21 may a driver under 18 carry in Texas?', ['No more than one', 'Up to three', 'As many as there are seat belts'], 0, 'A driver under 18 may not carry more than one passenger under 21 who is not a family member.'),
        q('How long must a minor hold a learner license before a Class C license?', ['At least six months', 'At least 30 days', 'At least one year'], 0, 'Texas will not issue a Class C license to an applicant under 18 unless the learner license has been held for at least six months.'),
        q('A driver under 18 is convicted of two moving violations within 12 months. What can happen?', ['The license can be suspended', 'Nothing until a third violation', 'Only a warning letter'], 0, 'Two or more moving-violation convictions within a 12-month period are a ground for suspending the license of a driver under 18.'),
        q('May a 17-year-old driver ignore the passenger restriction when the passengers are close friends?', ['No', 'Yes, if everyone wears a belt', 'Yes, after six months of driving'], 0, 'The one-passenger-under-21 limit applies to anyone who is not a family member, and it lasts until the driver turns 18.'),
      ],
    }),

    lesson('licenses-and-registration', {
      title: 'License, Registration, and Vehicle Transfer',
      objective: 'Different events create different people, forms, and deadlines.',
      keyPoints: ['Carry a valid license.', 'Match each deadline to the event.', 'Keep proof of submissions.'],
      rules: [
        'TX_TN_521_021_025_LICENSE_REQUIRED_CARRIED',
        'TX_TN_521_054_ADDRESS_CHANGE_30_DAYS',
        'TX_TN_502_040_REGISTRATION_30_DAYS',
        'TX_TN_501_145_147_TITLE_TRANSFER',
        'TX_TN_521_029_NEW_RESIDENT_90_DAYS',
      ],
      challenge: challenge(
        'You sold your car to a private buyer.',
        'Who tells the state?',
        ['Both of you, separately', 'Only the buyer', 'The insurance company'],
        0,
        'The buyer files the title transfer; the seller submits a vehicle transfer notification to protect themselves.',
        { image: 'licenses-and-registration-shared-01' },
      ),
      cards: [
        rule('Driving requires a valid license', [
          'You must not drive on a Texas highway without a driver license unless you are expressly exempt.',
          'Keep the license of the right class in your possession while driving and display it when a peace officer, magistrate, or court officer demands it.',
          'A first violation carries a fine of up to $200.',
        ]),
        rule('Address change: 30 days', [
          'Notify the Department of Public Safety within 30 days after a move or a name change, and apply for a duplicate license showing the new address.',
          'The duty is separate from vehicle registration, ownership transfer, or license renewal.',
          'Notices about renewals, suspensions, and hearings go to the address on file.',
        ]),
        image('licenses-and-registration-shared-01'),
        rule('Registration and title: 30 days', [
          'Within 30 days of buying a vehicle or becoming a Texas resident, apply to register it through your county tax assessor-collector, with proof of Texas insurance.',
          'The buyer of a used vehicle files the assigned title with the county within the same 30 days; active-duty military buyers have 60 days.',
          'A license shows the driving privilege; registration connects a vehicle to its operating record; the title records ownership.',
        ]),
        rule('New resident license: 90 days', [
          'A new Texas resident who is at least 16 may drive on a valid out-of-state license for no more than 90 days. Get the Texas license within that window.',
          'Thirty and 90 days are both correct Texas numbers for different events.',
          'Never choose the number before identifying the license, the vehicle, or the seller.',
        ]),
        recall('Recall · Deadlines', 'Register a vehicle and transfer a title within [[30 days]]. A new resident gets a Texas license within [[90 days]].'),
        image('licenses-and-registration-shared-02'),
        rule('The seller has a job too', [
          'After selling, submit a vehicle transfer notification to the Texas Department of Motor Vehicles, online or on paper.',
          'It records the vehicle, both parties, and the date you handed over possession. Do it promptly, before the buyer’s 30 days run out.',
          'Until the record changes, tickets and tolls on that car can still land on you.',
        ]),
        recall('Recall · Address change', 'Moved or changed your name? Notify the Department of Public Safety within [[30 days]] and get a [[duplicate]] license.'),
        remember('Match each deadline to the event', [
          'First identify who must act and what changed. A number is useful only when it matches the correct event.',
          'The person responsible for a filing acts immediately instead of waiting for another party.',
          'Keep the deadlines separate:',
        ], { bullets: ['Buyer’s title transfer and vehicle registration: 30 days.', 'License address or name change: 30 days.', 'New resident’s Texas license: 90 days.'] }),
      ],
      test: [
        q('You moved to Texas with a car registered in another state. When must you register it in Texas?', ['Within 30 days of becoming a resident', 'Within 90 days', 'When the old registration expires'], 0, 'The owner must apply for Texas registration within 30 days of purchasing a vehicle or becoming a Texas resident.'),
        q('Where must a licensed driver keep the valid license while driving?', ['In immediate possession', 'At home', 'Only in a digital photo'], 0, 'The possession rule requires the valid license to be immediately available while driving.'),
        q('How long does a Texas driver have to report a new address?', ['30 days', '10 days', '90 days'], 0, 'A license holder who moves must notify the Department of Public Safety within 30 days and apply for a duplicate license with the current address.'),
        q('How long may a new Texas resident with a valid out-of-state license drive before getting a Texas license?', ['No more than 90 days', 'No more than 30 days', 'One year'], 0, 'A new resident who is at least 16 and holds a valid license from the previous state or country may drive on it for up to 90 days after entering Texas.'),
        q('When must the buyer of a used vehicle file for title transfer in Texas?', ['Within 30 days of the title assignment', 'Within 5 days', 'Only when the registration renews'], 0, 'The buyer files the assigned title with the county tax assessor-collector within 30 days; active-duty military members have 60 days.'),
        q('After a private-party vehicle sale in Texas, who has a filing to make?', ['Both: the buyer transfers the title and the seller submits a transfer notification', 'Only the buyer', 'Only the seller'], 0, 'The buyer must file the title transfer within 30 days; the seller submits a vehicle transfer notification so the record no longer ties the car to them.'),
      ],
    }),

    lesson('penalties-and-points', {
      title: 'Suspensions, Penalties, and Police Stops',
      objective: 'The final questions often test consequences, not just driving moves.',
      keyPoints: ['Know how Texas counts convictions.', 'Know the DWI consequences.', 'Make traffic stops predictable.'],
      rules: [
        'TX_HANDBOOK_NO_POINT_SYSTEM',
        'TX_TN_521_292_SUSPENSION_GROUNDS',
        'TX_TN_724_011_035_IMPLIED_CONSENT_REFUSAL',
        'TX_TN_524_022_ALR_SUSPENSION',
        'TX_TN_601_051_072_FINANCIAL_RESPONSIBILITY',
        'TX_TN_521_246_IGNITION_INTERLOCK',
        'TX_TN_521_342_UNDER_21_ALCOHOL_SUSPENSION',
        'TX_TN_545_421_FLEEING_POLICE',
      ],
      challenge: challenge(
        'An officer activates emergency lights behind you.',
        'What should you do first?',
        ['Accelerate', 'Signal and pull over safely', 'Stop in the active lane when a shoulder is open'],
        1,
        'Choose a safe place, stop, and follow instructions. Refusing to stop for a police signal is a crime in Texas.',
        { image: 'penalties-and-points-shared-01' },
      ),
      cards: [
        rule('Texas has no point system', [
          'Texas does not add points to your record. It counts convictions instead.',
          'The old surcharge program that assigned points was repealed.',
          'Every moving-violation conviction still goes on the driving record, and the count itself can end your license. Insurance companies read the same record.',
        ]),
        rule('Remember the 4/12 and 7/24 pattern', [
          'A habitual violator has four or more moving-violation convictions from separate incidents in 12 consecutive months, or seven or more in 24 months. The Department of Public Safety suspends the license.',
          'For a driver under 18, two moving violations in 12 months are enough.',
          'Memorize the counts:',
        ], { bullets: ['Four in 12 months.', 'Seven in 24 months.', 'Under 18: two in 12 months.'] }),
        recall('Recall · Habitual violator', 'Texas has no points. [[Four]] moving violations in 12 months, or [[seven]] in 24, bring a suspension.'),
        image('penalties-and-points-shared-01'),
        rule('One event, one consequence', [
          'Different events trigger different license actions.',
          'A collision you caused with serious injury or serious property damage can bring a suspension.',
          'Refusing a chemical test after a DWI arrest costs 180 days on its own, and a failed test costs an adult 90 days.',
          'Driving without insurance brings a fine of $175 to $350 the first time. Do not mix these consequences.',
        ]),
        recall('Recall · Under 18', 'A driver under 18 with [[two]] moving violations in 12 months can lose the license.'),
        rule('DWI and hit-and-run bring more than a fine', [
          'Criminal, licensing, insurance, and financial consequences can overlap. Read the exact offense.',
          'After a DWI conviction with a suspension, the judge generally orders an ignition interlock device: a breath tester wired to the starter. No clean sample, no start.',
          'A driver under 21 convicted of DWI loses the license for one year.',
          'Insurance cost and eligibility can change.',
        ]),
        rule('Start a traffic stop safely', [
          'Signal and move to a safe place. Stop the vehicle and stay calm.',
          'Remain in the vehicle unless directed otherwise, and turn on the interior light at night.',
          'Have your license and proof of insurance ready; Texas requires you to show both on request.',
          'Keep your hands where they can be seen and explain before reaching for documents.',
        ]),
        image('penalties-and-points-shared-02'),
        rule('Never flee', [
          'Wilfully refusing to stop for a police signal is a crime and a ground for suspension. A safe stop is always the correct first move.',
          'Distractors often use words like always, never, automatic, or immediately while omitting a condition.',
          'Before choosing an exam answer, identify each condition:',
        ], { bullets: ['The driver involved', 'The type of road', 'The time window', 'The signal shown', 'Any stated exception'] }),
        recall('Recall · Traffic stops', 'Pulled over? Stop in a safe place, remain in the [[vehicle]], and keep your [[hands]] visible.'),
        remember('Final exam method', [
          'Final review is about conditions, not slogans.',
          'Penalties, suspensions, and exam numbers often look familiar; the correct answer connects each consequence to the exact violation, driver status, time window, and procedure.',
          'Use the same method on each exam question:',
        ], { bullets: ['Name the situation.', 'Remove unsafe answers.', 'Apply the Texas rule and the exact condition.'] }),
      ],
      test: [
        q('How does Texas track repeat traffic offenders?', ['By counting moving-violation convictions, not points', 'By a point system with a 12-point limit', 'By insurance company reports only'], 0, 'Texas has no point system; the Department of Public Safety suspends the license of a habitual violator based on conviction counts.'),
        q('How many moving-violation convictions in 12 consecutive months make a driver a habitual violator in Texas?', ['Four or more', 'Two or more', 'Ten or more'], 0, 'Four or more moving-violation convictions from separate incidents in 12 consecutive months, or seven or more in 24 months, make a habitual violator whose license is suspended.'),
        q('Which count matches the 24-month habitual-violator threshold?', ['Seven', 'Four', 'Twelve'], 0, 'Seven or more moving-violation convictions from separate incidents within 24 months bring a suspension.'),
        q('What does an ignition interlock device do?', ['Prevents the engine from starting until the driver gives an alcohol-free breath sample', 'Limits the vehicle’s top speed', 'Records the vehicle’s location for the court'], 0, 'After a DWI conviction with a suspension, the judge generally restricts the driver to a vehicle with an ignition interlock, a breath tester wired to the starter, at the driver’s expense.'),
        q('An answer gives the correct number but applies it to the wrong driver status. Is it correct?', ['No', 'Yes, the number is what matters', 'Only if the number is rounded'], 0, 'Exam answers pair a number with a condition; a correct number attached to the wrong driver, road, time, or exception is still wrong.'),
        q('An officer activates emergency lights behind you. What is the safest first response?', ['Signal and pull over safely, then follow instructions', 'Speed up to find a parking lot', 'Stop immediately in the travel lane'], 0, 'Signal, move to a safe place, stop, stay in the vehicle, and keep your hands visible; refusing to stop for a police signal is a crime.'),
      ],
    }),
  ],
};
