import { readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';

// The content schema is applied by the server from server/db/*.sql; the same
// files are copied into supabase/migrations for the record, the way every
// other migration of this project is kept. The copies must stay byte-identical
// — same idea as the wire.ts copies guarded by adminWireSync.test.ts.

const repoRoot = path.join(__dirname, '..');
const serverDir = path.join(repoRoot, 'server', 'db');

const serverFiles = readdirSync(serverDir)
  .filter(name => /^\d{4}_.*\.sql$/.test(name))
  .sort();

describe('content schema copies', () => {
  it('has at least the first content migration', () => {
    expect(serverFiles).toContain('0007_content_pipeline.sql');
  });

  it.each(serverFiles)('%s is byte-identical in supabase/migrations', name => {
    const server = readFileSync(path.join(serverDir, name), 'utf8');
    const supabase = readFileSync(
      path.join(repoRoot, 'supabase', 'migrations', name),
      'utf8',
    );

    expect(supabase).toBe(server);
  });
});

// The concept-emoji layer exists twice: scripts/emoji-layer.mjs, which the two
// pre-skeleton course builders still import, and server/src/admin/emojiLayer.mjs,
// which the builder that moved into the server imports. Both inject the same
// emoji into the same words, and a course generated by one has to read like a
// course generated by the other, so the two files are kept byte-identical the
// way the migrations are.
describe('the emoji layer', () => {
  it('is byte-identical in the server', () => {
    const here = readFileSync(
      path.join(__dirname, '..', 'scripts', 'emoji-layer.mjs'),
      'utf8',
    );
    const there = readFileSync(
      path.join(__dirname, '..', 'server', 'src', 'admin', 'emojiLayer.mjs'),
      'utf8',
    );
    expect(there).toBe(here);
  });
});
